// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solana-storage.proto

package solana.storage.ConfirmedBlock;

public interface ConfirmedTransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solana.storage.ConfirmedBlock.ConfirmedTransaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.solana.storage.ConfirmedBlock.Transaction transaction = 1;</code>
   * @return Whether the transaction field is set.
   */
  boolean hasTransaction();
  /**
   * <code>.solana.storage.ConfirmedBlock.Transaction transaction = 1;</code>
   * @return The transaction.
   */
  Transaction getTransaction();
  /**
   * <code>.solana.storage.ConfirmedBlock.Transaction transaction = 1;</code>
   */
  TransactionOrBuilder getTransactionOrBuilder();

  /**
   * <code>.solana.storage.ConfirmedBlock.TransactionStatusMeta meta = 2;</code>
   * @return Whether the meta field is set.
   */
  boolean hasMeta();
  /**
   * <code>.solana.storage.ConfirmedBlock.TransactionStatusMeta meta = 2;</code>
   * @return The meta.
   */
  TransactionStatusMeta getMeta();
  /**
   * <code>.solana.storage.ConfirmedBlock.TransactionStatusMeta meta = 2;</code>
   */
  TransactionStatusMetaOrBuilder getMetaOrBuilder();
}
