// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solana-storage.proto

package solana.storage.ConfirmedBlock;

/**
 * Protobuf type {@code solana.storage.ConfirmedBlock.InnerInstructions}
 */
public final class InnerInstructions extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:solana.storage.ConfirmedBlock.InnerInstructions)
    InnerInstructionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InnerInstructions.newBuilder() to construct.
  private InnerInstructions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InnerInstructions() {
    instructions_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new InnerInstructions();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_InnerInstructions_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_InnerInstructions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            InnerInstructions.class, Builder.class);
  }

  public static final int INDEX_FIELD_NUMBER = 1;
  private int index_;
  /**
   * <code>uint32 index = 1;</code>
   * @return The index.
   */
  @Override
  public int getIndex() {
    return index_;
  }

  public static final int INSTRUCTIONS_FIELD_NUMBER = 2;
  private java.util.List<InnerInstruction> instructions_;
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
   */
  @Override
  public java.util.List<InnerInstruction> getInstructionsList() {
    return instructions_;
  }
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
   */
  @Override
  public java.util.List<? extends InnerInstructionOrBuilder>
      getInstructionsOrBuilderList() {
    return instructions_;
  }
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
   */
  @Override
  public int getInstructionsCount() {
    return instructions_.size();
  }
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
   */
  @Override
  public InnerInstruction getInstructions(int index) {
    return instructions_.get(index);
  }
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
   */
  @Override
  public InnerInstructionOrBuilder getInstructionsOrBuilder(
      int index) {
    return instructions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (index_ != 0) {
      output.writeUInt32(1, index_);
    }
    for (int i = 0; i < instructions_.size(); i++) {
      output.writeMessage(2, instructions_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, index_);
    }
    for (int i = 0; i < instructions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, instructions_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof InnerInstructions)) {
      return super.equals(obj);
    }
    InnerInstructions other = (InnerInstructions) obj;

    if (getIndex()
        != other.getIndex()) return false;
    if (!getInstructionsList()
        .equals(other.getInstructionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    if (getInstructionsCount() > 0) {
      hash = (37 * hash) + INSTRUCTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getInstructionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static InnerInstructions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InnerInstructions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InnerInstructions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InnerInstructions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InnerInstructions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InnerInstructions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InnerInstructions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InnerInstructions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static InnerInstructions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static InnerInstructions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static InnerInstructions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InnerInstructions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(InnerInstructions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code solana.storage.ConfirmedBlock.InnerInstructions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:solana.storage.ConfirmedBlock.InnerInstructions)
      InnerInstructionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_InnerInstructions_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_InnerInstructions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InnerInstructions.class, Builder.class);
    }

    // Construct using solana.storage.ConfirmedBlock.InnerInstructions.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      index_ = 0;

      if (instructionsBuilder_ == null) {
        instructions_ = java.util.Collections.emptyList();
      } else {
        instructions_ = null;
        instructionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_InnerInstructions_descriptor;
    }

    @Override
    public InnerInstructions getDefaultInstanceForType() {
      return InnerInstructions.getDefaultInstance();
    }

    @Override
    public InnerInstructions build() {
      InnerInstructions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public InnerInstructions buildPartial() {
      InnerInstructions result = new InnerInstructions(this);
      int from_bitField0_ = bitField0_;
      result.index_ = index_;
      if (instructionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          instructions_ = java.util.Collections.unmodifiableList(instructions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.instructions_ = instructions_;
      } else {
        result.instructions_ = instructionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof InnerInstructions) {
        return mergeFrom((InnerInstructions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(InnerInstructions other) {
      if (other == InnerInstructions.getDefaultInstance()) return this;
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      if (instructionsBuilder_ == null) {
        if (!other.instructions_.isEmpty()) {
          if (instructions_.isEmpty()) {
            instructions_ = other.instructions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInstructionsIsMutable();
            instructions_.addAll(other.instructions_);
          }
          onChanged();
        }
      } else {
        if (!other.instructions_.isEmpty()) {
          if (instructionsBuilder_.isEmpty()) {
            instructionsBuilder_.dispose();
            instructionsBuilder_ = null;
            instructions_ = other.instructions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            instructionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInstructionsFieldBuilder() : null;
          } else {
            instructionsBuilder_.addAllMessages(other.instructions_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              index_ = input.readUInt32();

              break;
            } // case 8
            case 18: {
              InnerInstruction m =
                  input.readMessage(
                      InnerInstruction.parser(),
                      extensionRegistry);
              if (instructionsBuilder_ == null) {
                ensureInstructionsIsMutable();
                instructions_.add(m);
              } else {
                instructionsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int index_ ;
    /**
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    @Override
    public int getIndex() {
      return index_;
    }
    /**
     * <code>uint32 index = 1;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(int value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      
      index_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<InnerInstruction> instructions_ =
      java.util.Collections.emptyList();
    private void ensureInstructionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        instructions_ = new java.util.ArrayList<InnerInstruction>(instructions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        InnerInstruction, InnerInstruction.Builder, InnerInstructionOrBuilder> instructionsBuilder_;

    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public java.util.List<InnerInstruction> getInstructionsList() {
      if (instructionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(instructions_);
      } else {
        return instructionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public int getInstructionsCount() {
      if (instructionsBuilder_ == null) {
        return instructions_.size();
      } else {
        return instructionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public InnerInstruction getInstructions(int index) {
      if (instructionsBuilder_ == null) {
        return instructions_.get(index);
      } else {
        return instructionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public Builder setInstructions(
        int index, InnerInstruction value) {
      if (instructionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstructionsIsMutable();
        instructions_.set(index, value);
        onChanged();
      } else {
        instructionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public Builder setInstructions(
        int index, InnerInstruction.Builder builderForValue) {
      if (instructionsBuilder_ == null) {
        ensureInstructionsIsMutable();
        instructions_.set(index, builderForValue.build());
        onChanged();
      } else {
        instructionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public Builder addInstructions(InnerInstruction value) {
      if (instructionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstructionsIsMutable();
        instructions_.add(value);
        onChanged();
      } else {
        instructionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public Builder addInstructions(
        int index, InnerInstruction value) {
      if (instructionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstructionsIsMutable();
        instructions_.add(index, value);
        onChanged();
      } else {
        instructionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public Builder addInstructions(
        InnerInstruction.Builder builderForValue) {
      if (instructionsBuilder_ == null) {
        ensureInstructionsIsMutable();
        instructions_.add(builderForValue.build());
        onChanged();
      } else {
        instructionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public Builder addInstructions(
        int index, InnerInstruction.Builder builderForValue) {
      if (instructionsBuilder_ == null) {
        ensureInstructionsIsMutable();
        instructions_.add(index, builderForValue.build());
        onChanged();
      } else {
        instructionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public Builder addAllInstructions(
        Iterable<? extends InnerInstruction> values) {
      if (instructionsBuilder_ == null) {
        ensureInstructionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, instructions_);
        onChanged();
      } else {
        instructionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public Builder clearInstructions() {
      if (instructionsBuilder_ == null) {
        instructions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        instructionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public Builder removeInstructions(int index) {
      if (instructionsBuilder_ == null) {
        ensureInstructionsIsMutable();
        instructions_.remove(index);
        onChanged();
      } else {
        instructionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public InnerInstruction.Builder getInstructionsBuilder(
        int index) {
      return getInstructionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public InnerInstructionOrBuilder getInstructionsOrBuilder(
        int index) {
      if (instructionsBuilder_ == null) {
        return instructions_.get(index);  } else {
        return instructionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public java.util.List<? extends InnerInstructionOrBuilder>
         getInstructionsOrBuilderList() {
      if (instructionsBuilder_ != null) {
        return instructionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(instructions_);
      }
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public InnerInstruction.Builder addInstructionsBuilder() {
      return getInstructionsFieldBuilder().addBuilder(
          InnerInstruction.getDefaultInstance());
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public InnerInstruction.Builder addInstructionsBuilder(
        int index) {
      return getInstructionsFieldBuilder().addBuilder(
          index, InnerInstruction.getDefaultInstance());
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.InnerInstruction instructions = 2;</code>
     */
    public java.util.List<InnerInstruction.Builder>
         getInstructionsBuilderList() {
      return getInstructionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        InnerInstruction, InnerInstruction.Builder, InnerInstructionOrBuilder>
        getInstructionsFieldBuilder() {
      if (instructionsBuilder_ == null) {
        instructionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            InnerInstruction, InnerInstruction.Builder, InnerInstructionOrBuilder>(
                instructions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        instructions_ = null;
      }
      return instructionsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:solana.storage.ConfirmedBlock.InnerInstructions)
  }

  // @@protoc_insertion_point(class_scope:solana.storage.ConfirmedBlock.InnerInstructions)
  private static final InnerInstructions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new InnerInstructions();
  }

  public static InnerInstructions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InnerInstructions>
      PARSER = new com.google.protobuf.AbstractParser<InnerInstructions>() {
    @Override
    public InnerInstructions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InnerInstructions> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<InnerInstructions> getParserForType() {
    return PARSER;
  }

  @Override
  public InnerInstructions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

