// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solana-storage.proto

package solana.storage.ConfirmedBlock;

/**
 * Protobuf type {@code solana.storage.ConfirmedBlock.InnerInstruction}
 */
public final class InnerInstruction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:solana.storage.ConfirmedBlock.InnerInstruction)
    InnerInstructionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InnerInstruction.newBuilder() to construct.
  private InnerInstruction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InnerInstruction() {
    accounts_ = com.google.protobuf.ByteString.EMPTY;
    data_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new InnerInstruction();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_InnerInstruction_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_InnerInstruction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            InnerInstruction.class, Builder.class);
  }

  private int bitField0_;
  public static final int PROGRAM_ID_INDEX_FIELD_NUMBER = 1;
  private int programIdIndex_;
  /**
   * <code>uint32 program_id_index = 1;</code>
   * @return The programIdIndex.
   */
  @Override
  public int getProgramIdIndex() {
    return programIdIndex_;
  }

  public static final int ACCOUNTS_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString accounts_;
  /**
   * <code>bytes accounts = 2;</code>
   * @return The accounts.
   */
  @Override
  public com.google.protobuf.ByteString getAccounts() {
    return accounts_;
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  @Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int STACK_HEIGHT_FIELD_NUMBER = 4;
  private int stackHeight_;
  /**
   * <pre>
   * Invocation stack height of an inner instruction.
   * Available since Solana v1.14.6
   * Set to `None` for txs executed on earlier versions.
   * </pre>
   *
   * <code>optional uint32 stack_height = 4;</code>
   * @return Whether the stackHeight field is set.
   */
  @Override
  public boolean hasStackHeight() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Invocation stack height of an inner instruction.
   * Available since Solana v1.14.6
   * Set to `None` for txs executed on earlier versions.
   * </pre>
   *
   * <code>optional uint32 stack_height = 4;</code>
   * @return The stackHeight.
   */
  @Override
  public int getStackHeight() {
    return stackHeight_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (programIdIndex_ != 0) {
      output.writeUInt32(1, programIdIndex_);
    }
    if (!accounts_.isEmpty()) {
      output.writeBytes(2, accounts_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(3, data_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt32(4, stackHeight_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (programIdIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, programIdIndex_);
    }
    if (!accounts_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, accounts_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, data_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, stackHeight_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof InnerInstruction)) {
      return super.equals(obj);
    }
    InnerInstruction other = (InnerInstruction) obj;

    if (getProgramIdIndex()
        != other.getProgramIdIndex()) return false;
    if (!getAccounts()
        .equals(other.getAccounts())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (hasStackHeight() != other.hasStackHeight()) return false;
    if (hasStackHeight()) {
      if (getStackHeight()
          != other.getStackHeight()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROGRAM_ID_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getProgramIdIndex();
    hash = (37 * hash) + ACCOUNTS_FIELD_NUMBER;
    hash = (53 * hash) + getAccounts().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    if (hasStackHeight()) {
      hash = (37 * hash) + STACK_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getStackHeight();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static InnerInstruction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InnerInstruction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InnerInstruction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InnerInstruction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InnerInstruction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InnerInstruction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InnerInstruction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InnerInstruction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static InnerInstruction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static InnerInstruction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static InnerInstruction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InnerInstruction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(InnerInstruction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code solana.storage.ConfirmedBlock.InnerInstruction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:solana.storage.ConfirmedBlock.InnerInstruction)
      InnerInstructionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_InnerInstruction_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_InnerInstruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InnerInstruction.class, Builder.class);
    }

    // Construct using solana.storage.ConfirmedBlock.InnerInstruction.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      programIdIndex_ = 0;

      accounts_ = com.google.protobuf.ByteString.EMPTY;

      data_ = com.google.protobuf.ByteString.EMPTY;

      stackHeight_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_InnerInstruction_descriptor;
    }

    @Override
    public InnerInstruction getDefaultInstanceForType() {
      return InnerInstruction.getDefaultInstance();
    }

    @Override
    public InnerInstruction build() {
      InnerInstruction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public InnerInstruction buildPartial() {
      InnerInstruction result = new InnerInstruction(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.programIdIndex_ = programIdIndex_;
      result.accounts_ = accounts_;
      result.data_ = data_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.stackHeight_ = stackHeight_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof InnerInstruction) {
        return mergeFrom((InnerInstruction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(InnerInstruction other) {
      if (other == InnerInstruction.getDefaultInstance()) return this;
      if (other.getProgramIdIndex() != 0) {
        setProgramIdIndex(other.getProgramIdIndex());
      }
      if (other.getAccounts() != com.google.protobuf.ByteString.EMPTY) {
        setAccounts(other.getAccounts());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      if (other.hasStackHeight()) {
        setStackHeight(other.getStackHeight());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              programIdIndex_ = input.readUInt32();

              break;
            } // case 8
            case 18: {
              accounts_ = input.readBytes();

              break;
            } // case 18
            case 26: {
              data_ = input.readBytes();

              break;
            } // case 26
            case 32: {
              stackHeight_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int programIdIndex_ ;
    /**
     * <code>uint32 program_id_index = 1;</code>
     * @return The programIdIndex.
     */
    @Override
    public int getProgramIdIndex() {
      return programIdIndex_;
    }
    /**
     * <code>uint32 program_id_index = 1;</code>
     * @param value The programIdIndex to set.
     * @return This builder for chaining.
     */
    public Builder setProgramIdIndex(int value) {
      
      programIdIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 program_id_index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProgramIdIndex() {
      
      programIdIndex_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString accounts_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes accounts = 2;</code>
     * @return The accounts.
     */
    @Override
    public com.google.protobuf.ByteString getAccounts() {
      return accounts_;
    }
    /**
     * <code>bytes accounts = 2;</code>
     * @param value The accounts to set.
     * @return This builder for chaining.
     */
    public Builder setAccounts(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accounts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes accounts = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccounts() {
      
      accounts_ = getDefaultInstance().getAccounts();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 3;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes data = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private int stackHeight_ ;
    /**
     * <pre>
     * Invocation stack height of an inner instruction.
     * Available since Solana v1.14.6
     * Set to `None` for txs executed on earlier versions.
     * </pre>
     *
     * <code>optional uint32 stack_height = 4;</code>
     * @return Whether the stackHeight field is set.
     */
    @Override
    public boolean hasStackHeight() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Invocation stack height of an inner instruction.
     * Available since Solana v1.14.6
     * Set to `None` for txs executed on earlier versions.
     * </pre>
     *
     * <code>optional uint32 stack_height = 4;</code>
     * @return The stackHeight.
     */
    @Override
    public int getStackHeight() {
      return stackHeight_;
    }
    /**
     * <pre>
     * Invocation stack height of an inner instruction.
     * Available since Solana v1.14.6
     * Set to `None` for txs executed on earlier versions.
     * </pre>
     *
     * <code>optional uint32 stack_height = 4;</code>
     * @param value The stackHeight to set.
     * @return This builder for chaining.
     */
    public Builder setStackHeight(int value) {
      bitField0_ |= 0x00000001;
      stackHeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Invocation stack height of an inner instruction.
     * Available since Solana v1.14.6
     * Set to `None` for txs executed on earlier versions.
     * </pre>
     *
     * <code>optional uint32 stack_height = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStackHeight() {
      bitField0_ = (bitField0_ & ~0x00000001);
      stackHeight_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:solana.storage.ConfirmedBlock.InnerInstruction)
  }

  // @@protoc_insertion_point(class_scope:solana.storage.ConfirmedBlock.InnerInstruction)
  private static final InnerInstruction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new InnerInstruction();
  }

  public static InnerInstruction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InnerInstruction>
      PARSER = new com.google.protobuf.AbstractParser<InnerInstruction>() {
    @Override
    public InnerInstruction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InnerInstruction> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<InnerInstruction> getParserForType() {
    return PARSER;
  }

  @Override
  public InnerInstruction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

