// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solana-storage.proto

package solana.storage.ConfirmedBlock;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solana.storage.ConfirmedBlock.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.solana.storage.ConfirmedBlock.MessageHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.solana.storage.ConfirmedBlock.MessageHeader header = 1;</code>
   * @return The header.
   */
  MessageHeader getHeader();
  /**
   * <code>.solana.storage.ConfirmedBlock.MessageHeader header = 1;</code>
   */
  MessageHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated bytes account_keys = 2;</code>
   * @return A list containing the accountKeys.
   */
  java.util.List<com.google.protobuf.ByteString> getAccountKeysList();
  /**
   * <code>repeated bytes account_keys = 2;</code>
   * @return The count of accountKeys.
   */
  int getAccountKeysCount();
  /**
   * <code>repeated bytes account_keys = 2;</code>
   * @param index The index of the element to return.
   * @return The accountKeys at the given index.
   */
  com.google.protobuf.ByteString getAccountKeys(int index);

  /**
   * <code>bytes recent_blockhash = 3;</code>
   * @return The recentBlockhash.
   */
  com.google.protobuf.ByteString getRecentBlockhash();

  /**
   * <code>repeated .solana.storage.ConfirmedBlock.CompiledInstruction instructions = 4;</code>
   */
  java.util.List<CompiledInstruction>
      getInstructionsList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.CompiledInstruction instructions = 4;</code>
   */
  CompiledInstruction getInstructions(int index);
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.CompiledInstruction instructions = 4;</code>
   */
  int getInstructionsCount();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.CompiledInstruction instructions = 4;</code>
   */
  java.util.List<? extends CompiledInstructionOrBuilder>
      getInstructionsOrBuilderList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.CompiledInstruction instructions = 4;</code>
   */
  CompiledInstructionOrBuilder getInstructionsOrBuilder(
      int index);

  /**
   * <code>bool versioned = 5;</code>
   * @return The versioned.
   */
  boolean getVersioned();

  /**
   * <code>repeated .solana.storage.ConfirmedBlock.MessageAddressTableLookup address_table_lookups = 6;</code>
   */
  java.util.List<MessageAddressTableLookup>
      getAddressTableLookupsList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.MessageAddressTableLookup address_table_lookups = 6;</code>
   */
  MessageAddressTableLookup getAddressTableLookups(int index);
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.MessageAddressTableLookup address_table_lookups = 6;</code>
   */
  int getAddressTableLookupsCount();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.MessageAddressTableLookup address_table_lookups = 6;</code>
   */
  java.util.List<? extends MessageAddressTableLookupOrBuilder>
      getAddressTableLookupsOrBuilderList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.MessageAddressTableLookup address_table_lookups = 6;</code>
   */
  MessageAddressTableLookupOrBuilder getAddressTableLookupsOrBuilder(
      int index);
}
