// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solana-storage.proto

package solana.storage.ConfirmedBlock;

public interface RewardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solana.storage.ConfirmedBlock.Reward)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pubkey = 1;</code>
   * @return The pubkey.
   */
  String getPubkey();
  /**
   * <code>string pubkey = 1;</code>
   * @return The bytes for pubkey.
   */
  com.google.protobuf.ByteString
      getPubkeyBytes();

  /**
   * <code>int64 lamports = 2;</code>
   * @return The lamports.
   */
  long getLamports();

  /**
   * <code>uint64 post_balance = 3;</code>
   * @return The postBalance.
   */
  long getPostBalance();

  /**
   * <code>.solana.storage.ConfirmedBlock.RewardType reward_type = 4;</code>
   * @return The enum numeric value on the wire for rewardType.
   */
  int getRewardTypeValue();
  /**
   * <code>.solana.storage.ConfirmedBlock.RewardType reward_type = 4;</code>
   * @return The rewardType.
   */
  RewardType getRewardType();

  /**
   * <code>string commission = 5;</code>
   * @return The commission.
   */
  String getCommission();
  /**
   * <code>string commission = 5;</code>
   * @return The bytes for commission.
   */
  com.google.protobuf.ByteString
      getCommissionBytes();
}
