// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solana-storage.proto

package solana.storage.ConfirmedBlock;

/**
 * Protobuf type {@code solana.storage.ConfirmedBlock.Rewards}
 */
public final class Rewards extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:solana.storage.ConfirmedBlock.Rewards)
    RewardsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Rewards.newBuilder() to construct.
  private Rewards(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Rewards() {
    rewards_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Rewards();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_Rewards_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_Rewards_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Rewards.class, Builder.class);
  }

  public static final int REWARDS_FIELD_NUMBER = 1;
  private java.util.List<Reward> rewards_;
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
   */
  @Override
  public java.util.List<Reward> getRewardsList() {
    return rewards_;
  }
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
   */
  @Override
  public java.util.List<? extends RewardOrBuilder>
      getRewardsOrBuilderList() {
    return rewards_;
  }
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
   */
  @Override
  public int getRewardsCount() {
    return rewards_.size();
  }
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
   */
  @Override
  public Reward getRewards(int index) {
    return rewards_.get(index);
  }
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
   */
  @Override
  public RewardOrBuilder getRewardsOrBuilder(
      int index) {
    return rewards_.get(index);
  }

  public static final int NUM_PARTITIONS_FIELD_NUMBER = 2;
  private NumPartitions numPartitions_;
  /**
   * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
   * @return Whether the numPartitions field is set.
   */
  @Override
  public boolean hasNumPartitions() {
    return numPartitions_ != null;
  }
  /**
   * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
   * @return The numPartitions.
   */
  @Override
  public NumPartitions getNumPartitions() {
    return numPartitions_ == null ? NumPartitions.getDefaultInstance() : numPartitions_;
  }
  /**
   * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
   */
  @Override
  public NumPartitionsOrBuilder getNumPartitionsOrBuilder() {
    return getNumPartitions();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rewards_.size(); i++) {
      output.writeMessage(1, rewards_.get(i));
    }
    if (numPartitions_ != null) {
      output.writeMessage(2, getNumPartitions());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < rewards_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rewards_.get(i));
    }
    if (numPartitions_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getNumPartitions());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Rewards)) {
      return super.equals(obj);
    }
    Rewards other = (Rewards) obj;

    if (!getRewardsList()
        .equals(other.getRewardsList())) return false;
    if (hasNumPartitions() != other.hasNumPartitions()) return false;
    if (hasNumPartitions()) {
      if (!getNumPartitions()
          .equals(other.getNumPartitions())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRewardsCount() > 0) {
      hash = (37 * hash) + REWARDS_FIELD_NUMBER;
      hash = (53 * hash) + getRewardsList().hashCode();
    }
    if (hasNumPartitions()) {
      hash = (37 * hash) + NUM_PARTITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getNumPartitions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Rewards parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Rewards parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Rewards parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Rewards parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Rewards parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Rewards parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Rewards parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Rewards parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Rewards parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Rewards parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Rewards parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Rewards parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Rewards prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code solana.storage.ConfirmedBlock.Rewards}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:solana.storage.ConfirmedBlock.Rewards)
      RewardsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_Rewards_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_Rewards_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Rewards.class, Builder.class);
    }

    // Construct using solana.storage.ConfirmedBlock.Rewards.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      if (rewardsBuilder_ == null) {
        rewards_ = java.util.Collections.emptyList();
      } else {
        rewards_ = null;
        rewardsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (numPartitionsBuilder_ == null) {
        numPartitions_ = null;
      } else {
        numPartitions_ = null;
        numPartitionsBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SolanaStorage.internal_static_solana_storage_ConfirmedBlock_Rewards_descriptor;
    }

    @Override
    public Rewards getDefaultInstanceForType() {
      return Rewards.getDefaultInstance();
    }

    @Override
    public Rewards build() {
      Rewards result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Rewards buildPartial() {
      Rewards result = new Rewards(this);
      int from_bitField0_ = bitField0_;
      if (rewardsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          rewards_ = java.util.Collections.unmodifiableList(rewards_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rewards_ = rewards_;
      } else {
        result.rewards_ = rewardsBuilder_.build();
      }
      if (numPartitionsBuilder_ == null) {
        result.numPartitions_ = numPartitions_;
      } else {
        result.numPartitions_ = numPartitionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Rewards) {
        return mergeFrom((Rewards)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Rewards other) {
      if (other == Rewards.getDefaultInstance()) return this;
      if (rewardsBuilder_ == null) {
        if (!other.rewards_.isEmpty()) {
          if (rewards_.isEmpty()) {
            rewards_ = other.rewards_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRewardsIsMutable();
            rewards_.addAll(other.rewards_);
          }
          onChanged();
        }
      } else {
        if (!other.rewards_.isEmpty()) {
          if (rewardsBuilder_.isEmpty()) {
            rewardsBuilder_.dispose();
            rewardsBuilder_ = null;
            rewards_ = other.rewards_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rewardsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRewardsFieldBuilder() : null;
          } else {
            rewardsBuilder_.addAllMessages(other.rewards_);
          }
        }
      }
      if (other.hasNumPartitions()) {
        mergeNumPartitions(other.getNumPartitions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Reward m =
                  input.readMessage(
                      Reward.parser(),
                      extensionRegistry);
              if (rewardsBuilder_ == null) {
                ensureRewardsIsMutable();
                rewards_.add(m);
              } else {
                rewardsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getNumPartitionsFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<Reward> rewards_ =
      java.util.Collections.emptyList();
    private void ensureRewardsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        rewards_ = new java.util.ArrayList<Reward>(rewards_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Reward, Reward.Builder, RewardOrBuilder> rewardsBuilder_;

    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public java.util.List<Reward> getRewardsList() {
      if (rewardsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rewards_);
      } else {
        return rewardsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public int getRewardsCount() {
      if (rewardsBuilder_ == null) {
        return rewards_.size();
      } else {
        return rewardsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Reward getRewards(int index) {
      if (rewardsBuilder_ == null) {
        return rewards_.get(index);
      } else {
        return rewardsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Builder setRewards(
        int index, Reward value) {
      if (rewardsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRewardsIsMutable();
        rewards_.set(index, value);
        onChanged();
      } else {
        rewardsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Builder setRewards(
        int index, Reward.Builder builderForValue) {
      if (rewardsBuilder_ == null) {
        ensureRewardsIsMutable();
        rewards_.set(index, builderForValue.build());
        onChanged();
      } else {
        rewardsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Builder addRewards(Reward value) {
      if (rewardsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRewardsIsMutable();
        rewards_.add(value);
        onChanged();
      } else {
        rewardsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Builder addRewards(
        int index, Reward value) {
      if (rewardsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRewardsIsMutable();
        rewards_.add(index, value);
        onChanged();
      } else {
        rewardsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Builder addRewards(
        Reward.Builder builderForValue) {
      if (rewardsBuilder_ == null) {
        ensureRewardsIsMutable();
        rewards_.add(builderForValue.build());
        onChanged();
      } else {
        rewardsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Builder addRewards(
        int index, Reward.Builder builderForValue) {
      if (rewardsBuilder_ == null) {
        ensureRewardsIsMutable();
        rewards_.add(index, builderForValue.build());
        onChanged();
      } else {
        rewardsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Builder addAllRewards(
        Iterable<? extends Reward> values) {
      if (rewardsBuilder_ == null) {
        ensureRewardsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rewards_);
        onChanged();
      } else {
        rewardsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Builder clearRewards() {
      if (rewardsBuilder_ == null) {
        rewards_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rewardsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Builder removeRewards(int index) {
      if (rewardsBuilder_ == null) {
        ensureRewardsIsMutable();
        rewards_.remove(index);
        onChanged();
      } else {
        rewardsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Reward.Builder getRewardsBuilder(
        int index) {
      return getRewardsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public RewardOrBuilder getRewardsOrBuilder(
        int index) {
      if (rewardsBuilder_ == null) {
        return rewards_.get(index);  } else {
        return rewardsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public java.util.List<? extends RewardOrBuilder>
         getRewardsOrBuilderList() {
      if (rewardsBuilder_ != null) {
        return rewardsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rewards_);
      }
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Reward.Builder addRewardsBuilder() {
      return getRewardsFieldBuilder().addBuilder(
          Reward.getDefaultInstance());
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public Reward.Builder addRewardsBuilder(
        int index) {
      return getRewardsFieldBuilder().addBuilder(
          index, Reward.getDefaultInstance());
    }
    /**
     * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 1;</code>
     */
    public java.util.List<Reward.Builder>
         getRewardsBuilderList() {
      return getRewardsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Reward, Reward.Builder, RewardOrBuilder>
        getRewardsFieldBuilder() {
      if (rewardsBuilder_ == null) {
        rewardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Reward, Reward.Builder, RewardOrBuilder>(
                rewards_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        rewards_ = null;
      }
      return rewardsBuilder_;
    }

    private NumPartitions numPartitions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        NumPartitions, NumPartitions.Builder, NumPartitionsOrBuilder> numPartitionsBuilder_;
    /**
     * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
     * @return Whether the numPartitions field is set.
     */
    public boolean hasNumPartitions() {
      return numPartitionsBuilder_ != null || numPartitions_ != null;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
     * @return The numPartitions.
     */
    public NumPartitions getNumPartitions() {
      if (numPartitionsBuilder_ == null) {
        return numPartitions_ == null ? NumPartitions.getDefaultInstance() : numPartitions_;
      } else {
        return numPartitionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
     */
    public Builder setNumPartitions(NumPartitions value) {
      if (numPartitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        numPartitions_ = value;
        onChanged();
      } else {
        numPartitionsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
     */
    public Builder setNumPartitions(
        NumPartitions.Builder builderForValue) {
      if (numPartitionsBuilder_ == null) {
        numPartitions_ = builderForValue.build();
        onChanged();
      } else {
        numPartitionsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
     */
    public Builder mergeNumPartitions(NumPartitions value) {
      if (numPartitionsBuilder_ == null) {
        if (numPartitions_ != null) {
          numPartitions_ =
            NumPartitions.newBuilder(numPartitions_).mergeFrom(value).buildPartial();
        } else {
          numPartitions_ = value;
        }
        onChanged();
      } else {
        numPartitionsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
     */
    public Builder clearNumPartitions() {
      if (numPartitionsBuilder_ == null) {
        numPartitions_ = null;
        onChanged();
      } else {
        numPartitions_ = null;
        numPartitionsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
     */
    public NumPartitions.Builder getNumPartitionsBuilder() {
      
      onChanged();
      return getNumPartitionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
     */
    public NumPartitionsOrBuilder getNumPartitionsOrBuilder() {
      if (numPartitionsBuilder_ != null) {
        return numPartitionsBuilder_.getMessageOrBuilder();
      } else {
        return numPartitions_ == null ?
            NumPartitions.getDefaultInstance() : numPartitions_;
      }
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.NumPartitions num_partitions = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        NumPartitions, NumPartitions.Builder, NumPartitionsOrBuilder>
        getNumPartitionsFieldBuilder() {
      if (numPartitionsBuilder_ == null) {
        numPartitionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            NumPartitions, NumPartitions.Builder, NumPartitionsOrBuilder>(
                getNumPartitions(),
                getParentForChildren(),
                isClean());
        numPartitions_ = null;
      }
      return numPartitionsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:solana.storage.ConfirmedBlock.Rewards)
  }

  // @@protoc_insertion_point(class_scope:solana.storage.ConfirmedBlock.Rewards)
  private static final Rewards DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Rewards();
  }

  public static Rewards getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Rewards>
      PARSER = new com.google.protobuf.AbstractParser<Rewards>() {
    @Override
    public Rewards parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Rewards> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Rewards> getParserForType() {
    return PARSER;
  }

  @Override
  public Rewards getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

