// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solana-storage.proto

package solana.storage.ConfirmedBlock;

public interface TokenBalanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solana.storage.ConfirmedBlock.TokenBalance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 account_index = 1;</code>
   * @return The accountIndex.
   */
  int getAccountIndex();

  /**
   * <code>string mint = 2;</code>
   * @return The mint.
   */
  String getMint();
  /**
   * <code>string mint = 2;</code>
   * @return The bytes for mint.
   */
  com.google.protobuf.ByteString
      getMintBytes();

  /**
   * <code>.solana.storage.ConfirmedBlock.UiTokenAmount ui_token_amount = 3;</code>
   * @return Whether the uiTokenAmount field is set.
   */
  boolean hasUiTokenAmount();
  /**
   * <code>.solana.storage.ConfirmedBlock.UiTokenAmount ui_token_amount = 3;</code>
   * @return The uiTokenAmount.
   */
  UiTokenAmount getUiTokenAmount();
  /**
   * <code>.solana.storage.ConfirmedBlock.UiTokenAmount ui_token_amount = 3;</code>
   */
  UiTokenAmountOrBuilder getUiTokenAmountOrBuilder();

  /**
   * <code>string owner = 4;</code>
   * @return The owner.
   */
  String getOwner();
  /**
   * <code>string owner = 4;</code>
   * @return The bytes for owner.
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <code>string program_id = 5;</code>
   * @return The programId.
   */
  String getProgramId();
  /**
   * <code>string program_id = 5;</code>
   * @return The bytes for programId.
   */
  com.google.protobuf.ByteString
      getProgramIdBytes();
}
