// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solana-storage.proto

package solana.storage.ConfirmedBlock;

public interface TransactionStatusMetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solana.storage.ConfirmedBlock.TransactionStatusMeta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.solana.storage.ConfirmedBlock.TransactionError err = 1;</code>
   * @return Whether the err field is set.
   */
  boolean hasErr();
  /**
   * <code>.solana.storage.ConfirmedBlock.TransactionError err = 1;</code>
   * @return The err.
   */
  TransactionError getErr();
  /**
   * <code>.solana.storage.ConfirmedBlock.TransactionError err = 1;</code>
   */
  TransactionErrorOrBuilder getErrOrBuilder();

  /**
   * <code>uint64 fee = 2;</code>
   * @return The fee.
   */
  long getFee();

  /**
   * <code>repeated uint64 pre_balances = 3;</code>
   * @return A list containing the preBalances.
   */
  java.util.List<Long> getPreBalancesList();
  /**
   * <code>repeated uint64 pre_balances = 3;</code>
   * @return The count of preBalances.
   */
  int getPreBalancesCount();
  /**
   * <code>repeated uint64 pre_balances = 3;</code>
   * @param index The index of the element to return.
   * @return The preBalances at the given index.
   */
  long getPreBalances(int index);

  /**
   * <code>repeated uint64 post_balances = 4;</code>
   * @return A list containing the postBalances.
   */
  java.util.List<Long> getPostBalancesList();
  /**
   * <code>repeated uint64 post_balances = 4;</code>
   * @return The count of postBalances.
   */
  int getPostBalancesCount();
  /**
   * <code>repeated uint64 post_balances = 4;</code>
   * @param index The index of the element to return.
   * @return The postBalances at the given index.
   */
  long getPostBalances(int index);

  /**
   * <code>repeated .solana.storage.ConfirmedBlock.InnerInstructions inner_instructions = 5;</code>
   */
  java.util.List<InnerInstructions>
      getInnerInstructionsList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.InnerInstructions inner_instructions = 5;</code>
   */
  InnerInstructions getInnerInstructions(int index);
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.InnerInstructions inner_instructions = 5;</code>
   */
  int getInnerInstructionsCount();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.InnerInstructions inner_instructions = 5;</code>
   */
  java.util.List<? extends InnerInstructionsOrBuilder>
      getInnerInstructionsOrBuilderList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.InnerInstructions inner_instructions = 5;</code>
   */
  InnerInstructionsOrBuilder getInnerInstructionsOrBuilder(
      int index);

  /**
   * <code>bool inner_instructions_none = 10;</code>
   * @return The innerInstructionsNone.
   */
  boolean getInnerInstructionsNone();

  /**
   * <code>repeated string log_messages = 6;</code>
   * @return A list containing the logMessages.
   */
  java.util.List<String>
      getLogMessagesList();
  /**
   * <code>repeated string log_messages = 6;</code>
   * @return The count of logMessages.
   */
  int getLogMessagesCount();
  /**
   * <code>repeated string log_messages = 6;</code>
   * @param index The index of the element to return.
   * @return The logMessages at the given index.
   */
  String getLogMessages(int index);
  /**
   * <code>repeated string log_messages = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the logMessages at the given index.
   */
  com.google.protobuf.ByteString
      getLogMessagesBytes(int index);

  /**
   * <code>bool log_messages_none = 11;</code>
   * @return The logMessagesNone.
   */
  boolean getLogMessagesNone();

  /**
   * <code>repeated .solana.storage.ConfirmedBlock.TokenBalance pre_token_balances = 7;</code>
   */
  java.util.List<TokenBalance>
      getPreTokenBalancesList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.TokenBalance pre_token_balances = 7;</code>
   */
  TokenBalance getPreTokenBalances(int index);
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.TokenBalance pre_token_balances = 7;</code>
   */
  int getPreTokenBalancesCount();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.TokenBalance pre_token_balances = 7;</code>
   */
  java.util.List<? extends TokenBalanceOrBuilder>
      getPreTokenBalancesOrBuilderList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.TokenBalance pre_token_balances = 7;</code>
   */
  TokenBalanceOrBuilder getPreTokenBalancesOrBuilder(
      int index);

  /**
   * <code>repeated .solana.storage.ConfirmedBlock.TokenBalance post_token_balances = 8;</code>
   */
  java.util.List<TokenBalance>
      getPostTokenBalancesList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.TokenBalance post_token_balances = 8;</code>
   */
  TokenBalance getPostTokenBalances(int index);
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.TokenBalance post_token_balances = 8;</code>
   */
  int getPostTokenBalancesCount();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.TokenBalance post_token_balances = 8;</code>
   */
  java.util.List<? extends TokenBalanceOrBuilder>
      getPostTokenBalancesOrBuilderList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.TokenBalance post_token_balances = 8;</code>
   */
  TokenBalanceOrBuilder getPostTokenBalancesOrBuilder(
      int index);

  /**
   * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 9;</code>
   */
  java.util.List<Reward>
      getRewardsList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 9;</code>
   */
  Reward getRewards(int index);
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 9;</code>
   */
  int getRewardsCount();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 9;</code>
   */
  java.util.List<? extends RewardOrBuilder>
      getRewardsOrBuilderList();
  /**
   * <code>repeated .solana.storage.ConfirmedBlock.Reward rewards = 9;</code>
   */
  RewardOrBuilder getRewardsOrBuilder(
      int index);

  /**
   * <code>repeated bytes loaded_writable_addresses = 12;</code>
   * @return A list containing the loadedWritableAddresses.
   */
  java.util.List<com.google.protobuf.ByteString> getLoadedWritableAddressesList();
  /**
   * <code>repeated bytes loaded_writable_addresses = 12;</code>
   * @return The count of loadedWritableAddresses.
   */
  int getLoadedWritableAddressesCount();
  /**
   * <code>repeated bytes loaded_writable_addresses = 12;</code>
   * @param index The index of the element to return.
   * @return The loadedWritableAddresses at the given index.
   */
  com.google.protobuf.ByteString getLoadedWritableAddresses(int index);

  /**
   * <code>repeated bytes loaded_readonly_addresses = 13;</code>
   * @return A list containing the loadedReadonlyAddresses.
   */
  java.util.List<com.google.protobuf.ByteString> getLoadedReadonlyAddressesList();
  /**
   * <code>repeated bytes loaded_readonly_addresses = 13;</code>
   * @return The count of loadedReadonlyAddresses.
   */
  int getLoadedReadonlyAddressesCount();
  /**
   * <code>repeated bytes loaded_readonly_addresses = 13;</code>
   * @param index The index of the element to return.
   * @return The loadedReadonlyAddresses at the given index.
   */
  com.google.protobuf.ByteString getLoadedReadonlyAddresses(int index);

  /**
   * <code>.solana.storage.ConfirmedBlock.ReturnData return_data = 14;</code>
   * @return Whether the returnData field is set.
   */
  boolean hasReturnData();
  /**
   * <code>.solana.storage.ConfirmedBlock.ReturnData return_data = 14;</code>
   * @return The returnData.
   */
  ReturnData getReturnData();
  /**
   * <code>.solana.storage.ConfirmedBlock.ReturnData return_data = 14;</code>
   */
  ReturnDataOrBuilder getReturnDataOrBuilder();

  /**
   * <code>bool return_data_none = 15;</code>
   * @return The returnDataNone.
   */
  boolean getReturnDataNone();

  /**
   * <pre>
   * Sum of compute units consumed by all instructions.
   * Available since Solana v1.10.35 / v1.11.6.
   * Set to `None` for txs executed on earlier versions.
   * </pre>
   *
   * <code>optional uint64 compute_units_consumed = 16;</code>
   * @return Whether the computeUnitsConsumed field is set.
   */
  boolean hasComputeUnitsConsumed();
  /**
   * <pre>
   * Sum of compute units consumed by all instructions.
   * Available since Solana v1.10.35 / v1.11.6.
   * Set to `None` for txs executed on earlier versions.
   * </pre>
   *
   * <code>optional uint64 compute_units_consumed = 16;</code>
   * @return The computeUnitsConsumed.
   */
  long getComputeUnitsConsumed();
}
