// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

/**
 * Protobuf enum {@code geyser.CommitmentLevel}
 */
public enum CommitmentLevel
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PROCESSED = 0;</code>
   */
  PROCESSED(0),
  /**
   * <code>CONFIRMED = 1;</code>
   */
  CONFIRMED(1),
  /**
   * <code>FINALIZED = 2;</code>
   */
  FINALIZED(2),
  /**
   * <code>FIRST_SHRED_RECEIVED = 3;</code>
   */
  FIRST_SHRED_RECEIVED(3),
  /**
   * <code>COMPLETED = 4;</code>
   */
  COMPLETED(4),
  /**
   * <code>CREATED_BANK = 5;</code>
   */
  CREATED_BANK(5),
  /**
   * <code>DEAD = 6;</code>
   */
  DEAD(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PROCESSED = 0;</code>
   */
  public static final int PROCESSED_VALUE = 0;
  /**
   * <code>CONFIRMED = 1;</code>
   */
  public static final int CONFIRMED_VALUE = 1;
  /**
   * <code>FINALIZED = 2;</code>
   */
  public static final int FINALIZED_VALUE = 2;
  /**
   * <code>FIRST_SHRED_RECEIVED = 3;</code>
   */
  public static final int FIRST_SHRED_RECEIVED_VALUE = 3;
  /**
   * <code>COMPLETED = 4;</code>
   */
  public static final int COMPLETED_VALUE = 4;
  /**
   * <code>CREATED_BANK = 5;</code>
   */
  public static final int CREATED_BANK_VALUE = 5;
  /**
   * <code>DEAD = 6;</code>
   */
  public static final int DEAD_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static CommitmentLevel valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CommitmentLevel forNumber(int value) {
    switch (value) {
      case 0: return PROCESSED;
      case 1: return CONFIRMED;
      case 2: return FINALIZED;
      case 3: return FIRST_SHRED_RECEIVED;
      case 4: return COMPLETED;
      case 5: return CREATED_BANK;
      case 6: return DEAD;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CommitmentLevel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CommitmentLevel> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CommitmentLevel>() {
          public CommitmentLevel findValueByNumber(int number) {
            return CommitmentLevel.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return GeyserOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final CommitmentLevel[] VALUES = values();

  public static CommitmentLevel valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CommitmentLevel(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:geyser.CommitmentLevel)
}

