// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public interface GetBlockHeightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geyser.GetBlockHeightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 block_height = 1;</code>
   * @return The blockHeight.
   */
  long getBlockHeight();
}
