// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public interface GetLatestBlockhashRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geyser.GetLatestBlockhashRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .geyser.CommitmentLevel commitment = 1;</code>
   * @return Whether the commitment field is set.
   */
  boolean hasCommitment();
  /**
   * <code>optional .geyser.CommitmentLevel commitment = 1;</code>
   * @return The enum numeric value on the wire for commitment.
   */
  int getCommitmentValue();
  /**
   * <code>optional .geyser.CommitmentLevel commitment = 1;</code>
   * @return The commitment.
   */
  CommitmentLevel getCommitment();
}
