// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

/**
 * Protobuf type {@code geyser.GetLatestBlockhashResponse}
 */
public final class GetLatestBlockhashResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geyser.GetLatestBlockhashResponse)
    GetLatestBlockhashResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetLatestBlockhashResponse.newBuilder() to construct.
  private GetLatestBlockhashResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetLatestBlockhashResponse() {
    blockhash_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetLatestBlockhashResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GeyserOuterClass.internal_static_geyser_GetLatestBlockhashResponse_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GeyserOuterClass.internal_static_geyser_GetLatestBlockhashResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetLatestBlockhashResponse.class, Builder.class);
  }

  public static final int SLOT_FIELD_NUMBER = 1;
  private long slot_;
  /**
   * <code>uint64 slot = 1;</code>
   * @return The slot.
   */
  @Override
  public long getSlot() {
    return slot_;
  }

  public static final int BLOCKHASH_FIELD_NUMBER = 2;
  private volatile Object blockhash_;
  /**
   * <code>string blockhash = 2;</code>
   * @return The blockhash.
   */
  @Override
  public String getBlockhash() {
    Object ref = blockhash_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      blockhash_ = s;
      return s;
    }
  }
  /**
   * <code>string blockhash = 2;</code>
   * @return The bytes for blockhash.
   */
  @Override
  public com.google.protobuf.ByteString
      getBlockhashBytes() {
    Object ref = blockhash_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      blockhash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_VALID_BLOCK_HEIGHT_FIELD_NUMBER = 3;
  private long lastValidBlockHeight_;
  /**
   * <code>uint64 last_valid_block_height = 3;</code>
   * @return The lastValidBlockHeight.
   */
  @Override
  public long getLastValidBlockHeight() {
    return lastValidBlockHeight_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (slot_ != 0L) {
      output.writeUInt64(1, slot_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockhash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, blockhash_);
    }
    if (lastValidBlockHeight_ != 0L) {
      output.writeUInt64(3, lastValidBlockHeight_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (slot_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, slot_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockhash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, blockhash_);
    }
    if (lastValidBlockHeight_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, lastValidBlockHeight_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetLatestBlockhashResponse)) {
      return super.equals(obj);
    }
    GetLatestBlockhashResponse other = (GetLatestBlockhashResponse) obj;

    if (getSlot()
        != other.getSlot()) return false;
    if (!getBlockhash()
        .equals(other.getBlockhash())) return false;
    if (getLastValidBlockHeight()
        != other.getLastValidBlockHeight()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SLOT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSlot());
    hash = (37 * hash) + BLOCKHASH_FIELD_NUMBER;
    hash = (53 * hash) + getBlockhash().hashCode();
    hash = (37 * hash) + LAST_VALID_BLOCK_HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastValidBlockHeight());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetLatestBlockhashResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetLatestBlockhashResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetLatestBlockhashResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetLatestBlockhashResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetLatestBlockhashResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetLatestBlockhashResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetLatestBlockhashResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetLatestBlockhashResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetLatestBlockhashResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GetLatestBlockhashResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetLatestBlockhashResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetLatestBlockhashResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetLatestBlockhashResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geyser.GetLatestBlockhashResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geyser.GetLatestBlockhashResponse)
      GetLatestBlockhashResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GeyserOuterClass.internal_static_geyser_GetLatestBlockhashResponse_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GeyserOuterClass.internal_static_geyser_GetLatestBlockhashResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetLatestBlockhashResponse.class, Builder.class);
    }

    // Construct using geyser.GetLatestBlockhashResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      slot_ = 0L;

      blockhash_ = "";

      lastValidBlockHeight_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GeyserOuterClass.internal_static_geyser_GetLatestBlockhashResponse_descriptor;
    }

    @Override
    public GetLatestBlockhashResponse getDefaultInstanceForType() {
      return GetLatestBlockhashResponse.getDefaultInstance();
    }

    @Override
    public GetLatestBlockhashResponse build() {
      GetLatestBlockhashResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GetLatestBlockhashResponse buildPartial() {
      GetLatestBlockhashResponse result = new GetLatestBlockhashResponse(this);
      result.slot_ = slot_;
      result.blockhash_ = blockhash_;
      result.lastValidBlockHeight_ = lastValidBlockHeight_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetLatestBlockhashResponse) {
        return mergeFrom((GetLatestBlockhashResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetLatestBlockhashResponse other) {
      if (other == GetLatestBlockhashResponse.getDefaultInstance()) return this;
      if (other.getSlot() != 0L) {
        setSlot(other.getSlot());
      }
      if (!other.getBlockhash().isEmpty()) {
        blockhash_ = other.blockhash_;
        onChanged();
      }
      if (other.getLastValidBlockHeight() != 0L) {
        setLastValidBlockHeight(other.getLastValidBlockHeight());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              slot_ = input.readUInt64();

              break;
            } // case 8
            case 18: {
              blockhash_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 24: {
              lastValidBlockHeight_ = input.readUInt64();

              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private long slot_ ;
    /**
     * <code>uint64 slot = 1;</code>
     * @return The slot.
     */
    @Override
    public long getSlot() {
      return slot_;
    }
    /**
     * <code>uint64 slot = 1;</code>
     * @param value The slot to set.
     * @return This builder for chaining.
     */
    public Builder setSlot(long value) {
      
      slot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 slot = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlot() {
      
      slot_ = 0L;
      onChanged();
      return this;
    }

    private Object blockhash_ = "";
    /**
     * <code>string blockhash = 2;</code>
     * @return The blockhash.
     */
    public String getBlockhash() {
      Object ref = blockhash_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blockhash_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string blockhash = 2;</code>
     * @return The bytes for blockhash.
     */
    public com.google.protobuf.ByteString
        getBlockhashBytes() {
      Object ref = blockhash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        blockhash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string blockhash = 2;</code>
     * @param value The blockhash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockhash(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      blockhash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string blockhash = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockhash() {
      
      blockhash_ = getDefaultInstance().getBlockhash();
      onChanged();
      return this;
    }
    /**
     * <code>string blockhash = 2;</code>
     * @param value The bytes for blockhash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockhashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      blockhash_ = value;
      onChanged();
      return this;
    }

    private long lastValidBlockHeight_ ;
    /**
     * <code>uint64 last_valid_block_height = 3;</code>
     * @return The lastValidBlockHeight.
     */
    @Override
    public long getLastValidBlockHeight() {
      return lastValidBlockHeight_;
    }
    /**
     * <code>uint64 last_valid_block_height = 3;</code>
     * @param value The lastValidBlockHeight to set.
     * @return This builder for chaining.
     */
    public Builder setLastValidBlockHeight(long value) {
      
      lastValidBlockHeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 last_valid_block_height = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastValidBlockHeight() {
      
      lastValidBlockHeight_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geyser.GetLatestBlockhashResponse)
  }

  // @@protoc_insertion_point(class_scope:geyser.GetLatestBlockhashResponse)
  private static final GetLatestBlockhashResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetLatestBlockhashResponse();
  }

  public static GetLatestBlockhashResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLatestBlockhashResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetLatestBlockhashResponse>() {
    @Override
    public GetLatestBlockhashResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetLatestBlockhashResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetLatestBlockhashResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public GetLatestBlockhashResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

