// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public final class GeyserOuterClass {
  private GeyserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequest_AccountsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequest_AccountsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequest_SlotsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequest_SlotsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequest_TransactionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequest_TransactionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequest_TransactionsStatusEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequest_TransactionsStatusEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequest_BlocksEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequest_BlocksEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequest_BlocksMetaEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequest_BlocksMetaEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequest_EntryEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequest_EntryEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequestFilterAccounts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequestFilterAccounts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequestFilterAccountsFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequestFilterAccountsFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequestFilterAccountsFilterMemcmp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequestFilterAccountsFilterMemcmp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequestFilterAccountsFilterLamports_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequestFilterAccountsFilterLamports_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequestFilterSlots_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequestFilterSlots_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequestFilterTransactions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequestFilterTransactions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequestFilterBlocks_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequestFilterBlocks_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequestFilterBlocksMeta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequestFilterBlocksMeta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequestFilterEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequestFilterEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequestAccountsDataSlice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequestAccountsDataSlice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeRequestPing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeRequestPing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdateAccount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdateAccount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdateAccountInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdateAccountInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdateSlot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdateSlot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdateTransaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdateTransaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdateTransactionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdateTransactionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdateTransactionStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdateTransactionStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdateBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdateBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdateBlockMeta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdateBlockMeta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdateEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdatePing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdatePing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_SubscribeUpdatePong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_SubscribeUpdatePong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_PongResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_PongResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_GetLatestBlockhashRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_GetLatestBlockhashRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_GetLatestBlockhashResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_GetLatestBlockhashResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_GetBlockHeightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_GetBlockHeightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_GetBlockHeightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_GetBlockHeightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_GetSlotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_GetSlotRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_GetSlotResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_GetSlotResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_GetVersionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_GetVersionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_GetVersionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_GetVersionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_IsBlockhashValidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_IsBlockhashValidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geyser_IsBlockhashValidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geyser_IsBlockhashValidResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014geyser.proto\022\006geyser\032\037google/protobuf/" +
      "timestamp.proto\032\024solana-storage.proto\"\234\n" +
      "\n\020SubscribeRequest\0228\n\010accounts\030\001 \003(\0132&.g" +
      "eyser.SubscribeRequest.AccountsEntry\0222\n\005" +
      "slots\030\002 \003(\0132#.geyser.SubscribeRequest.Sl" +
      "otsEntry\022@\n\014transactions\030\003 \003(\0132*.geyser." +
      "SubscribeRequest.TransactionsEntry\022M\n\023tr" +
      "ansactions_status\030\n \003(\01320.geyser.Subscri" +
      "beRequest.TransactionsStatusEntry\0224\n\006blo" +
      "cks\030\004 \003(\0132$.geyser.SubscribeRequest.Bloc" +
      "ksEntry\022=\n\013blocks_meta\030\005 \003(\0132(.geyser.Su" +
      "bscribeRequest.BlocksMetaEntry\0222\n\005entry\030" +
      "\010 \003(\0132#.geyser.SubscribeRequest.EntryEnt" +
      "ry\0220\n\ncommitment\030\006 \001(\0162\027.geyser.Commitme" +
      "ntLevelH\000\210\001\001\022F\n\023accounts_data_slice\030\007 \003(" +
      "\0132).geyser.SubscribeRequestAccountsDataS" +
      "lice\022/\n\004ping\030\t \001(\0132\034.geyser.SubscribeReq" +
      "uestPingH\001\210\001\001\022\026\n\tfrom_slot\030\013 \001(\004H\002\210\001\001\032W\n" +
      "\rAccountsEntry\022\013\n\003key\030\001 \001(\t\0225\n\005value\030\002 \001" +
      "(\0132&.geyser.SubscribeRequestFilterAccoun" +
      "ts:\0028\001\032Q\n\nSlotsEntry\022\013\n\003key\030\001 \001(\t\0222\n\005val" +
      "ue\030\002 \001(\0132#.geyser.SubscribeRequestFilter" +
      "Slots:\0028\001\032_\n\021TransactionsEntry\022\013\n\003key\030\001 " +
      "\001(\t\0229\n\005value\030\002 \001(\0132*.geyser.SubscribeReq" +
      "uestFilterTransactions:\0028\001\032e\n\027Transactio" +
      "nsStatusEntry\022\013\n\003key\030\001 \001(\t\0229\n\005value\030\002 \001(" +
      "\0132*.geyser.SubscribeRequestFilterTransac" +
      "tions:\0028\001\032S\n\013BlocksEntry\022\013\n\003key\030\001 \001(\t\0223\n" +
      "\005value\030\002 \001(\0132$.geyser.SubscribeRequestFi" +
      "lterBlocks:\0028\001\032[\n\017BlocksMetaEntry\022\013\n\003key" +
      "\030\001 \001(\t\0227\n\005value\030\002 \001(\0132(.geyser.Subscribe" +
      "RequestFilterBlocksMeta:\0028\001\032Q\n\nEntryEntr" +
      "y\022\013\n\003key\030\001 \001(\t\0222\n\005value\030\002 \001(\0132#.geyser.S" +
      "ubscribeRequestFilterEntry:\0028\001B\r\n\013_commi" +
      "tmentB\007\n\005_pingB\014\n\n_from_slot\"\277\001\n\036Subscri" +
      "beRequestFilterAccounts\022\017\n\007account\030\002 \003(\t" +
      "\022\r\n\005owner\030\003 \003(\t\022=\n\007filters\030\004 \003(\0132,.geyse" +
      "r.SubscribeRequestFilterAccountsFilter\022#" +
      "\n\026nonempty_txn_signature\030\005 \001(\010H\000\210\001\001B\031\n\027_" +
      "nonempty_txn_signature\"\363\001\n$SubscribeRequ" +
      "estFilterAccountsFilter\022D\n\006memcmp\030\001 \001(\0132" +
      "2.geyser.SubscribeRequestFilterAccountsF" +
      "ilterMemcmpH\000\022\022\n\010datasize\030\002 \001(\004H\000\022\035\n\023tok" +
      "en_account_state\030\003 \001(\010H\000\022H\n\010lamports\030\004 \001" +
      "(\01324.geyser.SubscribeRequestFilterAccoun" +
      "tsFilterLamportsH\000B\010\n\006filter\"y\n*Subscrib" +
      "eRequestFilterAccountsFilterMemcmp\022\016\n\006of" +
      "fset\030\001 \001(\004\022\017\n\005bytes\030\002 \001(\014H\000\022\020\n\006base58\030\003 " +
      "\001(\tH\000\022\020\n\006base64\030\004 \001(\tH\000B\006\n\004data\"m\n,Subsc" +
      "ribeRequestFilterAccountsFilterLamports\022" +
      "\014\n\002eq\030\001 \001(\004H\000\022\014\n\002ne\030\002 \001(\004H\000\022\014\n\002lt\030\003 \001(\004H" +
      "\000\022\014\n\002gt\030\004 \001(\004H\000B\005\n\003cmp\"Y\n\033SubscribeReque" +
      "stFilterSlots\022!\n\024filter_by_commitment\030\001 " +
      "\001(\010H\000\210\001\001B\027\n\025_filter_by_commitment\"\322\001\n\"Su" +
      "bscribeRequestFilterTransactions\022\021\n\004vote" +
      "\030\001 \001(\010H\000\210\001\001\022\023\n\006failed\030\002 \001(\010H\001\210\001\001\022\026\n\tsign" +
      "ature\030\005 \001(\tH\002\210\001\001\022\027\n\017account_include\030\003 \003(" +
      "\t\022\027\n\017account_exclude\030\004 \003(\t\022\030\n\020account_re" +
      "quired\030\006 \003(\tB\007\n\005_voteB\t\n\007_failedB\014\n\n_sig" +
      "nature\"\331\001\n\034SubscribeRequestFilterBlocks\022" +
      "\027\n\017account_include\030\001 \003(\t\022!\n\024include_tran" +
      "sactions\030\002 \001(\010H\000\210\001\001\022\035\n\020include_accounts\030" +
      "\003 \001(\010H\001\210\001\001\022\034\n\017include_entries\030\004 \001(\010H\002\210\001\001" +
      "B\027\n\025_include_transactionsB\023\n\021_include_ac" +
      "countsB\022\n\020_include_entries\"\"\n SubscribeR" +
      "equestFilterBlocksMeta\"\035\n\033SubscribeReque" +
      "stFilterEntry\"C\n!SubscribeRequestAccount" +
      "sDataSlice\022\016\n\006offset\030\001 \001(\004\022\016\n\006length\030\002 \001" +
      "(\004\"\"\n\024SubscribeRequestPing\022\n\n\002id\030\001 \001(\005\"\265" +
      "\004\n\017SubscribeUpdate\022\017\n\007filters\030\001 \003(\t\0221\n\007a" +
      "ccount\030\002 \001(\0132\036.geyser.SubscribeUpdateAcc" +
      "ountH\000\022+\n\004slot\030\003 \001(\0132\033.geyser.SubscribeU" +
      "pdateSlotH\000\0229\n\013transaction\030\004 \001(\0132\".geyse" +
      "r.SubscribeUpdateTransactionH\000\022F\n\022transa" +
      "ction_status\030\n \001(\0132(.geyser.SubscribeUpd" +
      "ateTransactionStatusH\000\022-\n\005block\030\005 \001(\0132\034." +
      "geyser.SubscribeUpdateBlockH\000\022+\n\004ping\030\006 " +
      "\001(\0132\033.geyser.SubscribeUpdatePingH\000\022+\n\004po" +
      "ng\030\t \001(\0132\033.geyser.SubscribeUpdatePongH\000\022" +
      "6\n\nblock_meta\030\007 \001(\0132 .geyser.SubscribeUp" +
      "dateBlockMetaH\000\022-\n\005entry\030\010 \001(\0132\034.geyser." +
      "SubscribeUpdateEntryH\000\022.\n\ncreated_at\030\013 \001" +
      "(\0132\032.google.protobuf.TimestampB\016\n\014update" +
      "_oneof\"o\n\026SubscribeUpdateAccount\0223\n\007acco" +
      "unt\030\001 \001(\0132\".geyser.SubscribeUpdateAccoun" +
      "tInfo\022\014\n\004slot\030\002 \001(\004\022\022\n\nis_startup\030\003 \001(\010\"" +
      "\310\001\n\032SubscribeUpdateAccountInfo\022\016\n\006pubkey" +
      "\030\001 \001(\014\022\020\n\010lamports\030\002 \001(\004\022\r\n\005owner\030\003 \001(\014\022" +
      "\022\n\nexecutable\030\004 \001(\010\022\022\n\nrent_epoch\030\005 \001(\004\022" +
      "\014\n\004data\030\006 \001(\014\022\025\n\rwrite_version\030\007 \001(\004\022\032\n\r" +
      "txn_signature\030\010 \001(\014H\000\210\001\001B\020\n\016_txn_signatu" +
      "re\"\224\001\n\023SubscribeUpdateSlot\022\014\n\004slot\030\001 \001(\004" +
      "\022\023\n\006parent\030\002 \001(\004H\000\210\001\001\022\'\n\006status\030\003 \001(\0162\027." +
      "geyser.CommitmentLevel\022\027\n\ndead_error\030\004 \001" +
      "(\tH\001\210\001\001B\t\n\007_parentB\r\n\013_dead_error\"g\n\032Sub" +
      "scribeUpdateTransaction\022;\n\013transaction\030\001" +
      " \001(\0132&.geyser.SubscribeUpdateTransaction" +
      "Info\022\014\n\004slot\030\002 \001(\004\"\330\001\n\036SubscribeUpdateTr" +
      "ansactionInfo\022\021\n\tsignature\030\001 \001(\014\022\017\n\007is_v" +
      "ote\030\002 \001(\010\022?\n\013transaction\030\003 \001(\0132*.solana." +
      "storage.ConfirmedBlock.Transaction\022B\n\004me" +
      "ta\030\004 \001(\01324.solana.storage.ConfirmedBlock" +
      ".TransactionStatusMeta\022\r\n\005index\030\005 \001(\004\"\241\001" +
      "\n SubscribeUpdateTransactionStatus\022\014\n\004sl" +
      "ot\030\001 \001(\004\022\021\n\tsignature\030\002 \001(\014\022\017\n\007is_vote\030\003" +
      " \001(\010\022\r\n\005index\030\004 \001(\004\022<\n\003err\030\005 \001(\0132/.solan" +
      "a.storage.ConfirmedBlock.TransactionErro" +
      "r\"\240\004\n\024SubscribeUpdateBlock\022\014\n\004slot\030\001 \001(\004" +
      "\022\021\n\tblockhash\030\002 \001(\t\0227\n\007rewards\030\003 \001(\0132&.s" +
      "olana.storage.ConfirmedBlock.Rewards\022@\n\n" +
      "block_time\030\004 \001(\0132,.solana.storage.Confir" +
      "medBlock.UnixTimestamp\022@\n\014block_height\030\005" +
      " \001(\0132*.solana.storage.ConfirmedBlock.Blo" +
      "ckHeight\022\023\n\013parent_slot\030\007 \001(\004\022\030\n\020parent_" +
      "blockhash\030\010 \001(\t\022\"\n\032executed_transaction_" +
      "count\030\t \001(\004\022<\n\014transactions\030\006 \003(\0132&.geys" +
      "er.SubscribeUpdateTransactionInfo\022\035\n\025upd" +
      "ated_account_count\030\n \001(\004\0224\n\010accounts\030\013 \003" +
      "(\0132\".geyser.SubscribeUpdateAccountInfo\022\025" +
      "\n\rentries_count\030\014 \001(\004\022-\n\007entries\030\r \003(\0132\034" +
      ".geyser.SubscribeUpdateEntry\"\342\002\n\030Subscri" +
      "beUpdateBlockMeta\022\014\n\004slot\030\001 \001(\004\022\021\n\tblock" +
      "hash\030\002 \001(\t\0227\n\007rewards\030\003 \001(\0132&.solana.sto" +
      "rage.ConfirmedBlock.Rewards\022@\n\nblock_tim" +
      "e\030\004 \001(\0132,.solana.storage.ConfirmedBlock." +
      "UnixTimestamp\022@\n\014block_height\030\005 \001(\0132*.so" +
      "lana.storage.ConfirmedBlock.BlockHeight\022" +
      "\023\n\013parent_slot\030\006 \001(\004\022\030\n\020parent_blockhash" +
      "\030\007 \001(\t\022\"\n\032executed_transaction_count\030\010 \001" +
      "(\004\022\025\n\rentries_count\030\t \001(\004\"\235\001\n\024SubscribeU" +
      "pdateEntry\022\014\n\004slot\030\001 \001(\004\022\r\n\005index\030\002 \001(\004\022" +
      "\022\n\nnum_hashes\030\003 \001(\004\022\014\n\004hash\030\004 \001(\014\022\"\n\032exe" +
      "cuted_transaction_count\030\005 \001(\004\022\"\n\032startin" +
      "g_transaction_index\030\006 \001(\004\"\025\n\023SubscribeUp" +
      "datePing\"!\n\023SubscribeUpdatePong\022\n\n\002id\030\001 " +
      "\001(\005\"\034\n\013PingRequest\022\r\n\005count\030\001 \001(\005\"\035\n\014Pon" +
      "gResponse\022\r\n\005count\030\001 \001(\005\"\\\n\031GetLatestBlo" +
      "ckhashRequest\0220\n\ncommitment\030\001 \001(\0162\027.geys" +
      "er.CommitmentLevelH\000\210\001\001B\r\n\013_commitment\"^" +
      "\n\032GetLatestBlockhashResponse\022\014\n\004slot\030\001 \001" +
      "(\004\022\021\n\tblockhash\030\002 \001(\t\022\037\n\027last_valid_bloc" +
      "k_height\030\003 \001(\004\"X\n\025GetBlockHeightRequest\022" +
      "0\n\ncommitment\030\001 \001(\0162\027.geyser.CommitmentL" +
      "evelH\000\210\001\001B\r\n\013_commitment\".\n\026GetBlockHeig" +
      "htResponse\022\024\n\014block_height\030\001 \001(\004\"Q\n\016GetS" +
      "lotRequest\0220\n\ncommitment\030\001 \001(\0162\027.geyser." +
      "CommitmentLevelH\000\210\001\001B\r\n\013_commitment\"\037\n\017G" +
      "etSlotResponse\022\014\n\004slot\030\001 \001(\004\"\023\n\021GetVersi" +
      "onRequest\"%\n\022GetVersionResponse\022\017\n\007versi" +
      "on\030\001 \001(\t\"m\n\027IsBlockhashValidRequest\022\021\n\tb" +
      "lockhash\030\001 \001(\t\0220\n\ncommitment\030\002 \001(\0162\027.gey" +
      "ser.CommitmentLevelH\000\210\001\001B\r\n\013_commitment\"" +
      "7\n\030IsBlockhashValidResponse\022\014\n\004slot\030\001 \001(" +
      "\004\022\r\n\005valid\030\002 \001(\010*\203\001\n\017CommitmentLevel\022\r\n\t" +
      "PROCESSED\020\000\022\r\n\tCONFIRMED\020\001\022\r\n\tFINALIZED\020" +
      "\002\022\030\n\024FIRST_SHRED_RECEIVED\020\003\022\r\n\tCOMPLETED" +
      "\020\004\022\020\n\014CREATED_BANK\020\005\022\010\n\004DEAD\020\0062\223\004\n\006Geyse" +
      "r\022D\n\tSubscribe\022\030.geyser.SubscribeRequest" +
      "\032\027.geyser.SubscribeUpdate\"\000(\0010\001\0223\n\004Ping\022" +
      "\023.geyser.PingRequest\032\024.geyser.PongRespon" +
      "se\"\000\022]\n\022GetLatestBlockhash\022!.geyser.GetL" +
      "atestBlockhashRequest\032\".geyser.GetLatest" +
      "BlockhashResponse\"\000\022Q\n\016GetBlockHeight\022\035." +
      "geyser.GetBlockHeightRequest\032\036.geyser.Ge" +
      "tBlockHeightResponse\"\000\022<\n\007GetSlot\022\026.geys" +
      "er.GetSlotRequest\032\027.geyser.GetSlotRespon" +
      "se\"\000\022W\n\020IsBlockhashValid\022\037.geyser.IsBloc" +
      "khashValidRequest\032 .geyser.IsBlockhashVa" +
      "lidResponse\"\000\022E\n\nGetVersion\022\031.geyser.Get" +
      "VersionRequest\032\032.geyser.GetVersionRespon" +
      "se\"\000B=P\001Z9github.com/rpcpool/yellowstone" +
      "-grpc/examples/golang/protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          solana.storage.ConfirmedBlock.SolanaStorage.getDescriptor(),
        });
    internal_static_geyser_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_geyser_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequest_descriptor,
        new String[] { "Accounts", "Slots", "Transactions", "TransactionsStatus", "Blocks", "BlocksMeta", "Entry", "Commitment", "AccountsDataSlice", "Ping", "FromSlot", "Commitment", "Ping", "FromSlot", });
    internal_static_geyser_SubscribeRequest_AccountsEntry_descriptor =
      internal_static_geyser_SubscribeRequest_descriptor.getNestedTypes().get(0);
    internal_static_geyser_SubscribeRequest_AccountsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequest_AccountsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_geyser_SubscribeRequest_SlotsEntry_descriptor =
      internal_static_geyser_SubscribeRequest_descriptor.getNestedTypes().get(1);
    internal_static_geyser_SubscribeRequest_SlotsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequest_SlotsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_geyser_SubscribeRequest_TransactionsEntry_descriptor =
      internal_static_geyser_SubscribeRequest_descriptor.getNestedTypes().get(2);
    internal_static_geyser_SubscribeRequest_TransactionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequest_TransactionsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_geyser_SubscribeRequest_TransactionsStatusEntry_descriptor =
      internal_static_geyser_SubscribeRequest_descriptor.getNestedTypes().get(3);
    internal_static_geyser_SubscribeRequest_TransactionsStatusEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequest_TransactionsStatusEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_geyser_SubscribeRequest_BlocksEntry_descriptor =
      internal_static_geyser_SubscribeRequest_descriptor.getNestedTypes().get(4);
    internal_static_geyser_SubscribeRequest_BlocksEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequest_BlocksEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_geyser_SubscribeRequest_BlocksMetaEntry_descriptor =
      internal_static_geyser_SubscribeRequest_descriptor.getNestedTypes().get(5);
    internal_static_geyser_SubscribeRequest_BlocksMetaEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequest_BlocksMetaEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_geyser_SubscribeRequest_EntryEntry_descriptor =
      internal_static_geyser_SubscribeRequest_descriptor.getNestedTypes().get(6);
    internal_static_geyser_SubscribeRequest_EntryEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequest_EntryEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_geyser_SubscribeRequestFilterAccounts_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_geyser_SubscribeRequestFilterAccounts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequestFilterAccounts_descriptor,
        new String[] { "Account", "Owner", "Filters", "NonemptyTxnSignature", "NonemptyTxnSignature", });
    internal_static_geyser_SubscribeRequestFilterAccountsFilter_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_geyser_SubscribeRequestFilterAccountsFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequestFilterAccountsFilter_descriptor,
        new String[] { "Memcmp", "Datasize", "TokenAccountState", "Lamports", "Filter", });
    internal_static_geyser_SubscribeRequestFilterAccountsFilterMemcmp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_geyser_SubscribeRequestFilterAccountsFilterMemcmp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequestFilterAccountsFilterMemcmp_descriptor,
        new String[] { "Offset", "Bytes", "Base58", "Base64", "Data", });
    internal_static_geyser_SubscribeRequestFilterAccountsFilterLamports_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_geyser_SubscribeRequestFilterAccountsFilterLamports_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequestFilterAccountsFilterLamports_descriptor,
        new String[] { "Eq", "Ne", "Lt", "Gt", "Cmp", });
    internal_static_geyser_SubscribeRequestFilterSlots_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_geyser_SubscribeRequestFilterSlots_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequestFilterSlots_descriptor,
        new String[] { "FilterByCommitment", "FilterByCommitment", });
    internal_static_geyser_SubscribeRequestFilterTransactions_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_geyser_SubscribeRequestFilterTransactions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequestFilterTransactions_descriptor,
        new String[] { "Vote", "Failed", "Signature", "AccountInclude", "AccountExclude", "AccountRequired", "Vote", "Failed", "Signature", });
    internal_static_geyser_SubscribeRequestFilterBlocks_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_geyser_SubscribeRequestFilterBlocks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequestFilterBlocks_descriptor,
        new String[] { "AccountInclude", "IncludeTransactions", "IncludeAccounts", "IncludeEntries", "IncludeTransactions", "IncludeAccounts", "IncludeEntries", });
    internal_static_geyser_SubscribeRequestFilterBlocksMeta_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_geyser_SubscribeRequestFilterBlocksMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequestFilterBlocksMeta_descriptor,
        new String[] { });
    internal_static_geyser_SubscribeRequestFilterEntry_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_geyser_SubscribeRequestFilterEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequestFilterEntry_descriptor,
        new String[] { });
    internal_static_geyser_SubscribeRequestAccountsDataSlice_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_geyser_SubscribeRequestAccountsDataSlice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequestAccountsDataSlice_descriptor,
        new String[] { "Offset", "Length", });
    internal_static_geyser_SubscribeRequestPing_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_geyser_SubscribeRequestPing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeRequestPing_descriptor,
        new String[] { "Id", });
    internal_static_geyser_SubscribeUpdate_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_geyser_SubscribeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdate_descriptor,
        new String[] { "Filters", "Account", "Slot", "Transaction", "TransactionStatus", "Block", "Ping", "Pong", "BlockMeta", "Entry", "CreatedAt", "UpdateOneof", });
    internal_static_geyser_SubscribeUpdateAccount_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_geyser_SubscribeUpdateAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdateAccount_descriptor,
        new String[] { "Account", "Slot", "IsStartup", });
    internal_static_geyser_SubscribeUpdateAccountInfo_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_geyser_SubscribeUpdateAccountInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdateAccountInfo_descriptor,
        new String[] { "Pubkey", "Lamports", "Owner", "Executable", "RentEpoch", "Data", "WriteVersion", "TxnSignature", "TxnSignature", });
    internal_static_geyser_SubscribeUpdateSlot_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_geyser_SubscribeUpdateSlot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdateSlot_descriptor,
        new String[] { "Slot", "Parent", "Status", "DeadError", "Parent", "DeadError", });
    internal_static_geyser_SubscribeUpdateTransaction_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_geyser_SubscribeUpdateTransaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdateTransaction_descriptor,
        new String[] { "Transaction", "Slot", });
    internal_static_geyser_SubscribeUpdateTransactionInfo_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_geyser_SubscribeUpdateTransactionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdateTransactionInfo_descriptor,
        new String[] { "Signature", "IsVote", "Transaction", "Meta", "Index", });
    internal_static_geyser_SubscribeUpdateTransactionStatus_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_geyser_SubscribeUpdateTransactionStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdateTransactionStatus_descriptor,
        new String[] { "Slot", "Signature", "IsVote", "Index", "Err", });
    internal_static_geyser_SubscribeUpdateBlock_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_geyser_SubscribeUpdateBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdateBlock_descriptor,
        new String[] { "Slot", "Blockhash", "Rewards", "BlockTime", "BlockHeight", "ParentSlot", "ParentBlockhash", "ExecutedTransactionCount", "Transactions", "UpdatedAccountCount", "Accounts", "EntriesCount12", "Entries13", });
    internal_static_geyser_SubscribeUpdateBlockMeta_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_geyser_SubscribeUpdateBlockMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdateBlockMeta_descriptor,
        new String[] { "Slot", "Blockhash", "Rewards", "BlockTime", "BlockHeight", "ParentSlot", "ParentBlockhash", "ExecutedTransactionCount", "EntriesCount", });
    internal_static_geyser_SubscribeUpdateEntry_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_geyser_SubscribeUpdateEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdateEntry_descriptor,
        new String[] { "Slot", "Index", "NumHashes", "Hash", "ExecutedTransactionCount", "StartingTransactionIndex", });
    internal_static_geyser_SubscribeUpdatePing_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_geyser_SubscribeUpdatePing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdatePing_descriptor,
        new String[] { });
    internal_static_geyser_SubscribeUpdatePong_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_geyser_SubscribeUpdatePong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_SubscribeUpdatePong_descriptor,
        new String[] { "Id", });
    internal_static_geyser_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_geyser_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_PingRequest_descriptor,
        new String[] { "Count", });
    internal_static_geyser_PongResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_geyser_PongResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_PongResponse_descriptor,
        new String[] { "Count", });
    internal_static_geyser_GetLatestBlockhashRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_geyser_GetLatestBlockhashRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_GetLatestBlockhashRequest_descriptor,
        new String[] { "Commitment", "Commitment", });
    internal_static_geyser_GetLatestBlockhashResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_geyser_GetLatestBlockhashResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_GetLatestBlockhashResponse_descriptor,
        new String[] { "Slot", "Blockhash", "LastValidBlockHeight", });
    internal_static_geyser_GetBlockHeightRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_geyser_GetBlockHeightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_GetBlockHeightRequest_descriptor,
        new String[] { "Commitment", "Commitment", });
    internal_static_geyser_GetBlockHeightResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_geyser_GetBlockHeightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_GetBlockHeightResponse_descriptor,
        new String[] { "BlockHeight", });
    internal_static_geyser_GetSlotRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_geyser_GetSlotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_GetSlotRequest_descriptor,
        new String[] { "Commitment", "Commitment", });
    internal_static_geyser_GetSlotResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_geyser_GetSlotResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_GetSlotResponse_descriptor,
        new String[] { "Slot", });
    internal_static_geyser_GetVersionRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_geyser_GetVersionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_GetVersionRequest_descriptor,
        new String[] { });
    internal_static_geyser_GetVersionResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_geyser_GetVersionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_GetVersionResponse_descriptor,
        new String[] { "Version", });
    internal_static_geyser_IsBlockhashValidRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_geyser_IsBlockhashValidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_IsBlockhashValidRequest_descriptor,
        new String[] { "Blockhash", "Commitment", "Commitment", });
    internal_static_geyser_IsBlockhashValidResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_geyser_IsBlockhashValidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geyser_IsBlockhashValidResponse_descriptor,
        new String[] { "Slot", "Valid", });
    com.google.protobuf.TimestampProto.getDescriptor();
    solana.storage.ConfirmedBlock.SolanaStorage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
