// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public interface IsBlockhashValidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geyser.IsBlockhashValidRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string blockhash = 1;</code>
   * @return The blockhash.
   */
  String getBlockhash();
  /**
   * <code>string blockhash = 1;</code>
   * @return The bytes for blockhash.
   */
  com.google.protobuf.ByteString
      getBlockhashBytes();

  /**
   * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
   * @return Whether the commitment field is set.
   */
  boolean hasCommitment();
  /**
   * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
   * @return The enum numeric value on the wire for commitment.
   */
  int getCommitmentValue();
  /**
   * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
   * @return The commitment.
   */
  CommitmentLevel getCommitment();
}
