// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public interface IsBlockhashValidResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geyser.IsBlockhashValidResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 slot = 1;</code>
   * @return The slot.
   */
  long getSlot();

  /**
   * <code>bool valid = 2;</code>
   * @return The valid.
   */
  boolean getValid();
}
