// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

/**
 * Protobuf type {@code geyser.IsBlockhashValidRequest}
 */
public final class IsBlockhashValidRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geyser.IsBlockhashValidRequest)
    IsBlockhashValidRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IsBlockhashValidRequest.newBuilder() to construct.
  private IsBlockhashValidRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IsBlockhashValidRequest() {
    blockhash_ = "";
    commitment_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new IsBlockhashValidRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GeyserOuterClass.internal_static_geyser_IsBlockhashValidRequest_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GeyserOuterClass.internal_static_geyser_IsBlockhashValidRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            IsBlockhashValidRequest.class, Builder.class);
  }

  private int bitField0_;
  public static final int BLOCKHASH_FIELD_NUMBER = 1;
  private volatile Object blockhash_;
  /**
   * <code>string blockhash = 1;</code>
   * @return The blockhash.
   */
  @Override
  public String getBlockhash() {
    Object ref = blockhash_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      blockhash_ = s;
      return s;
    }
  }
  /**
   * <code>string blockhash = 1;</code>
   * @return The bytes for blockhash.
   */
  @Override
  public com.google.protobuf.ByteString
      getBlockhashBytes() {
    Object ref = blockhash_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      blockhash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMITMENT_FIELD_NUMBER = 2;
  private int commitment_;
  /**
   * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
   * @return Whether the commitment field is set.
   */
  @Override public boolean hasCommitment() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
   * @return The enum numeric value on the wire for commitment.
   */
  @Override public int getCommitmentValue() {
    return commitment_;
  }
  /**
   * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
   * @return The commitment.
   */
  @Override public CommitmentLevel getCommitment() {
    @SuppressWarnings("deprecation")
    CommitmentLevel result = CommitmentLevel.valueOf(commitment_);
    return result == null ? CommitmentLevel.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockhash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, blockhash_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(2, commitment_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockhash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, blockhash_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, commitment_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof IsBlockhashValidRequest)) {
      return super.equals(obj);
    }
    IsBlockhashValidRequest other = (IsBlockhashValidRequest) obj;

    if (!getBlockhash()
        .equals(other.getBlockhash())) return false;
    if (hasCommitment() != other.hasCommitment()) return false;
    if (hasCommitment()) {
      if (commitment_ != other.commitment_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOCKHASH_FIELD_NUMBER;
    hash = (53 * hash) + getBlockhash().hashCode();
    if (hasCommitment()) {
      hash = (37 * hash) + COMMITMENT_FIELD_NUMBER;
      hash = (53 * hash) + commitment_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static IsBlockhashValidRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IsBlockhashValidRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IsBlockhashValidRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IsBlockhashValidRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IsBlockhashValidRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IsBlockhashValidRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IsBlockhashValidRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static IsBlockhashValidRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static IsBlockhashValidRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static IsBlockhashValidRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static IsBlockhashValidRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static IsBlockhashValidRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(IsBlockhashValidRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geyser.IsBlockhashValidRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geyser.IsBlockhashValidRequest)
      IsBlockhashValidRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GeyserOuterClass.internal_static_geyser_IsBlockhashValidRequest_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GeyserOuterClass.internal_static_geyser_IsBlockhashValidRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IsBlockhashValidRequest.class, Builder.class);
    }

    // Construct using geyser.IsBlockhashValidRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      blockhash_ = "";

      commitment_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GeyserOuterClass.internal_static_geyser_IsBlockhashValidRequest_descriptor;
    }

    @Override
    public IsBlockhashValidRequest getDefaultInstanceForType() {
      return IsBlockhashValidRequest.getDefaultInstance();
    }

    @Override
    public IsBlockhashValidRequest build() {
      IsBlockhashValidRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public IsBlockhashValidRequest buildPartial() {
      IsBlockhashValidRequest result = new IsBlockhashValidRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.blockhash_ = blockhash_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.commitment_ = commitment_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof IsBlockhashValidRequest) {
        return mergeFrom((IsBlockhashValidRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(IsBlockhashValidRequest other) {
      if (other == IsBlockhashValidRequest.getDefaultInstance()) return this;
      if (!other.getBlockhash().isEmpty()) {
        blockhash_ = other.blockhash_;
        onChanged();
      }
      if (other.hasCommitment()) {
        setCommitment(other.getCommitment());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              blockhash_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              commitment_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object blockhash_ = "";
    /**
     * <code>string blockhash = 1;</code>
     * @return The blockhash.
     */
    public String getBlockhash() {
      Object ref = blockhash_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blockhash_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string blockhash = 1;</code>
     * @return The bytes for blockhash.
     */
    public com.google.protobuf.ByteString
        getBlockhashBytes() {
      Object ref = blockhash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        blockhash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string blockhash = 1;</code>
     * @param value The blockhash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockhash(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      blockhash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string blockhash = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockhash() {
      
      blockhash_ = getDefaultInstance().getBlockhash();
      onChanged();
      return this;
    }
    /**
     * <code>string blockhash = 1;</code>
     * @param value The bytes for blockhash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockhashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      blockhash_ = value;
      onChanged();
      return this;
    }

    private int commitment_ = 0;
    /**
     * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
     * @return Whether the commitment field is set.
     */
    @Override public boolean hasCommitment() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
     * @return The enum numeric value on the wire for commitment.
     */
    @Override public int getCommitmentValue() {
      return commitment_;
    }
    /**
     * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
     * @param value The enum numeric value on the wire for commitment to set.
     * @return This builder for chaining.
     */
    public Builder setCommitmentValue(int value) {
      bitField0_ |= 0x00000001;
      commitment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
     * @return The commitment.
     */
    @Override
    public CommitmentLevel getCommitment() {
      @SuppressWarnings("deprecation")
      CommitmentLevel result = CommitmentLevel.valueOf(commitment_);
      return result == null ? CommitmentLevel.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
     * @param value The commitment to set.
     * @return This builder for chaining.
     */
    public Builder setCommitment(CommitmentLevel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      commitment_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .geyser.CommitmentLevel commitment = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommitment() {
      bitField0_ = (bitField0_ & ~0x00000001);
      commitment_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geyser.IsBlockhashValidRequest)
  }

  // @@protoc_insertion_point(class_scope:geyser.IsBlockhashValidRequest)
  private static final IsBlockhashValidRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new IsBlockhashValidRequest();
  }

  public static IsBlockhashValidRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IsBlockhashValidRequest>
      PARSER = new com.google.protobuf.AbstractParser<IsBlockhashValidRequest>() {
    @Override
    public IsBlockhashValidRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IsBlockhashValidRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<IsBlockhashValidRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public IsBlockhashValidRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

