// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public interface SubscribeRequestFilterSlotsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geyser.SubscribeRequestFilterSlots)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool filter_by_commitment = 1;</code>
   * @return Whether the filterByCommitment field is set.
   */
  boolean hasFilterByCommitment();
  /**
   * <code>optional bool filter_by_commitment = 1;</code>
   * @return The filterByCommitment.
   */
  boolean getFilterByCommitment();
}
