// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public interface SubscribeRequestAccountsDataSliceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geyser.SubscribeRequestAccountsDataSlice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 offset = 1;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <code>uint64 length = 2;</code>
   * @return The length.
   */
  long getLength();
}
