// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public interface SubscribeRequestFilterBlocksMetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geyser.SubscribeRequestFilterBlocksMeta)
    com.google.protobuf.MessageOrBuilder {
}
