// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

/**
 * Protobuf type {@code geyser.SubscribeUpdateBlock}
 */
public final class SubscribeUpdateBlock extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geyser.SubscribeUpdateBlock)
    SubscribeUpdateBlockOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubscribeUpdateBlock.newBuilder() to construct.
  private SubscribeUpdateBlock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubscribeUpdateBlock() {
    blockhash_ = "";
    parentBlockhash_ = "";
    transactions_ = java.util.Collections.emptyList();
    accounts_ = java.util.Collections.emptyList();
    entries13_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubscribeUpdateBlock();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GeyserOuterClass.internal_static_geyser_SubscribeUpdateBlock_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GeyserOuterClass.internal_static_geyser_SubscribeUpdateBlock_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SubscribeUpdateBlock.class, Builder.class);
  }

  public static final int SLOT_FIELD_NUMBER = 1;
  private long slot_;
  /**
   * <code>uint64 slot = 1;</code>
   * @return The slot.
   */
  @Override
  public long getSlot() {
    return slot_;
  }

  public static final int BLOCKHASH_FIELD_NUMBER = 2;
  private volatile Object blockhash_;
  /**
   * <code>string blockhash = 2;</code>
   * @return The blockhash.
   */
  @Override
  public String getBlockhash() {
    Object ref = blockhash_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      blockhash_ = s;
      return s;
    }
  }
  /**
   * <code>string blockhash = 2;</code>
   * @return The bytes for blockhash.
   */
  @Override
  public com.google.protobuf.ByteString
      getBlockhashBytes() {
    Object ref = blockhash_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      blockhash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REWARDS_FIELD_NUMBER = 3;
  private solana.storage.ConfirmedBlock.Rewards rewards_;
  /**
   * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
   * @return Whether the rewards field is set.
   */
  @Override
  public boolean hasRewards() {
    return rewards_ != null;
  }
  /**
   * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
   * @return The rewards.
   */
  @Override
  public solana.storage.ConfirmedBlock.Rewards getRewards() {
    return rewards_ == null ? solana.storage.ConfirmedBlock.Rewards.getDefaultInstance() : rewards_;
  }
  /**
   * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
   */
  @Override
  public solana.storage.ConfirmedBlock.RewardsOrBuilder getRewardsOrBuilder() {
    return getRewards();
  }

  public static final int BLOCK_TIME_FIELD_NUMBER = 4;
  private solana.storage.ConfirmedBlock.UnixTimestamp blockTime_;
  /**
   * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
   * @return Whether the blockTime field is set.
   */
  @Override
  public boolean hasBlockTime() {
    return blockTime_ != null;
  }
  /**
   * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
   * @return The blockTime.
   */
  @Override
  public solana.storage.ConfirmedBlock.UnixTimestamp getBlockTime() {
    return blockTime_ == null ? solana.storage.ConfirmedBlock.UnixTimestamp.getDefaultInstance() : blockTime_;
  }
  /**
   * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
   */
  @Override
  public solana.storage.ConfirmedBlock.UnixTimestampOrBuilder getBlockTimeOrBuilder() {
    return getBlockTime();
  }

  public static final int BLOCK_HEIGHT_FIELD_NUMBER = 5;
  private solana.storage.ConfirmedBlock.BlockHeight blockHeight_;
  /**
   * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
   * @return Whether the blockHeight field is set.
   */
  @Override
  public boolean hasBlockHeight() {
    return blockHeight_ != null;
  }
  /**
   * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
   * @return The blockHeight.
   */
  @Override
  public solana.storage.ConfirmedBlock.BlockHeight getBlockHeight() {
    return blockHeight_ == null ? solana.storage.ConfirmedBlock.BlockHeight.getDefaultInstance() : blockHeight_;
  }
  /**
   * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
   */
  @Override
  public solana.storage.ConfirmedBlock.BlockHeightOrBuilder getBlockHeightOrBuilder() {
    return getBlockHeight();
  }

  public static final int PARENT_SLOT_FIELD_NUMBER = 7;
  private long parentSlot_;
  /**
   * <code>uint64 parent_slot = 7;</code>
   * @return The parentSlot.
   */
  @Override
  public long getParentSlot() {
    return parentSlot_;
  }

  public static final int PARENT_BLOCKHASH_FIELD_NUMBER = 8;
  private volatile Object parentBlockhash_;
  /**
   * <code>string parent_blockhash = 8;</code>
   * @return The parentBlockhash.
   */
  @Override
  public String getParentBlockhash() {
    Object ref = parentBlockhash_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      parentBlockhash_ = s;
      return s;
    }
  }
  /**
   * <code>string parent_blockhash = 8;</code>
   * @return The bytes for parentBlockhash.
   */
  @Override
  public com.google.protobuf.ByteString
      getParentBlockhashBytes() {
    Object ref = parentBlockhash_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      parentBlockhash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXECUTED_TRANSACTION_COUNT_FIELD_NUMBER = 9;
  private long executedTransactionCount_;
  /**
   * <code>uint64 executed_transaction_count = 9;</code>
   * @return The executedTransactionCount.
   */
  @Override
  public long getExecutedTransactionCount() {
    return executedTransactionCount_;
  }

  public static final int TRANSACTIONS_FIELD_NUMBER = 6;
  private java.util.List<SubscribeUpdateTransactionInfo> transactions_;
  /**
   * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
   */
  @Override
  public java.util.List<SubscribeUpdateTransactionInfo> getTransactionsList() {
    return transactions_;
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
   */
  @Override
  public java.util.List<? extends SubscribeUpdateTransactionInfoOrBuilder>
      getTransactionsOrBuilderList() {
    return transactions_;
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
   */
  @Override
  public int getTransactionsCount() {
    return transactions_.size();
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
   */
  @Override
  public SubscribeUpdateTransactionInfo getTransactions(int index) {
    return transactions_.get(index);
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
   */
  @Override
  public SubscribeUpdateTransactionInfoOrBuilder getTransactionsOrBuilder(
      int index) {
    return transactions_.get(index);
  }

  public static final int UPDATED_ACCOUNT_COUNT_FIELD_NUMBER = 10;
  private long updatedAccountCount_;
  /**
   * <code>uint64 updated_account_count = 10;</code>
   * @return The updatedAccountCount.
   */
  @Override
  public long getUpdatedAccountCount() {
    return updatedAccountCount_;
  }

  public static final int ACCOUNTS_FIELD_NUMBER = 11;
  private java.util.List<SubscribeUpdateAccountInfo> accounts_;
  /**
   * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
   */
  @Override
  public java.util.List<SubscribeUpdateAccountInfo> getAccountsList() {
    return accounts_;
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
   */
  @Override
  public java.util.List<? extends SubscribeUpdateAccountInfoOrBuilder>
      getAccountsOrBuilderList() {
    return accounts_;
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
   */
  @Override
  public int getAccountsCount() {
    return accounts_.size();
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
   */
  @Override
  public SubscribeUpdateAccountInfo getAccounts(int index) {
    return accounts_.get(index);
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
   */
  @Override
  public SubscribeUpdateAccountInfoOrBuilder getAccountsOrBuilder(
      int index) {
    return accounts_.get(index);
  }

  public static final int ENTRIES_COUNT_FIELD_NUMBER = 12;
  private long entriesCount12_;
  // An alternative name is used for field "entries_count" because:
  //     both repeated field "entries" and singular field "entries_count" generate the method "getEntriesCount()"
  /**
   * <code>uint64 entries_count = 12;</code>
   * @return The entriesCount.
   */
  @Override
  public long getEntriesCount12() {
    return entriesCount12_;
  }

  public static final int ENTRIES_FIELD_NUMBER = 13;
  private java.util.List<SubscribeUpdateEntry> entries13_;
  // An alternative name is used for field "entries" because:
  //     both repeated field "entries" and singular field "entries_count" generate the method "getEntriesCount()"
  /**
   * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
   */
  @Override
  public java.util.List<SubscribeUpdateEntry> getEntries13List() {
    return entries13_;
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
   */
  @Override
  public java.util.List<? extends SubscribeUpdateEntryOrBuilder>
      getEntries13OrBuilderList() {
    return entries13_;
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
   */
  @Override
  public int getEntries13Count() {
    return entries13_.size();
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
   */
  @Override
  public SubscribeUpdateEntry getEntries13(int index) {
    return entries13_.get(index);
  }
  /**
   * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
   */
  @Override
  public SubscribeUpdateEntryOrBuilder getEntries13OrBuilder(
      int index) {
    return entries13_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (slot_ != 0L) {
      output.writeUInt64(1, slot_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockhash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, blockhash_);
    }
    if (rewards_ != null) {
      output.writeMessage(3, getRewards());
    }
    if (blockTime_ != null) {
      output.writeMessage(4, getBlockTime());
    }
    if (blockHeight_ != null) {
      output.writeMessage(5, getBlockHeight());
    }
    for (int i = 0; i < transactions_.size(); i++) {
      output.writeMessage(6, transactions_.get(i));
    }
    if (parentSlot_ != 0L) {
      output.writeUInt64(7, parentSlot_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentBlockhash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, parentBlockhash_);
    }
    if (executedTransactionCount_ != 0L) {
      output.writeUInt64(9, executedTransactionCount_);
    }
    if (updatedAccountCount_ != 0L) {
      output.writeUInt64(10, updatedAccountCount_);
    }
    for (int i = 0; i < accounts_.size(); i++) {
      output.writeMessage(11, accounts_.get(i));
    }
    if (entriesCount12_ != 0L) {
      output.writeUInt64(12, entriesCount12_);
    }
    for (int i = 0; i < entries13_.size(); i++) {
      output.writeMessage(13, entries13_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (slot_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, slot_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockhash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, blockhash_);
    }
    if (rewards_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRewards());
    }
    if (blockTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getBlockTime());
    }
    if (blockHeight_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getBlockHeight());
    }
    for (int i = 0; i < transactions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, transactions_.get(i));
    }
    if (parentSlot_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, parentSlot_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentBlockhash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, parentBlockhash_);
    }
    if (executedTransactionCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, executedTransactionCount_);
    }
    if (updatedAccountCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(10, updatedAccountCount_);
    }
    for (int i = 0; i < accounts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, accounts_.get(i));
    }
    if (entriesCount12_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(12, entriesCount12_);
    }
    for (int i = 0; i < entries13_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, entries13_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SubscribeUpdateBlock)) {
      return super.equals(obj);
    }
    SubscribeUpdateBlock other = (SubscribeUpdateBlock) obj;

    if (getSlot()
        != other.getSlot()) return false;
    if (!getBlockhash()
        .equals(other.getBlockhash())) return false;
    if (hasRewards() != other.hasRewards()) return false;
    if (hasRewards()) {
      if (!getRewards()
          .equals(other.getRewards())) return false;
    }
    if (hasBlockTime() != other.hasBlockTime()) return false;
    if (hasBlockTime()) {
      if (!getBlockTime()
          .equals(other.getBlockTime())) return false;
    }
    if (hasBlockHeight() != other.hasBlockHeight()) return false;
    if (hasBlockHeight()) {
      if (!getBlockHeight()
          .equals(other.getBlockHeight())) return false;
    }
    if (getParentSlot()
        != other.getParentSlot()) return false;
    if (!getParentBlockhash()
        .equals(other.getParentBlockhash())) return false;
    if (getExecutedTransactionCount()
        != other.getExecutedTransactionCount()) return false;
    if (!getTransactionsList()
        .equals(other.getTransactionsList())) return false;
    if (getUpdatedAccountCount()
        != other.getUpdatedAccountCount()) return false;
    if (!getAccountsList()
        .equals(other.getAccountsList())) return false;
    if (getEntriesCount12()
        != other.getEntriesCount12()) return false;
    if (!getEntries13List()
        .equals(other.getEntries13List())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SLOT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSlot());
    hash = (37 * hash) + BLOCKHASH_FIELD_NUMBER;
    hash = (53 * hash) + getBlockhash().hashCode();
    if (hasRewards()) {
      hash = (37 * hash) + REWARDS_FIELD_NUMBER;
      hash = (53 * hash) + getRewards().hashCode();
    }
    if (hasBlockTime()) {
      hash = (37 * hash) + BLOCK_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getBlockTime().hashCode();
    }
    if (hasBlockHeight()) {
      hash = (37 * hash) + BLOCK_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getBlockHeight().hashCode();
    }
    hash = (37 * hash) + PARENT_SLOT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getParentSlot());
    hash = (37 * hash) + PARENT_BLOCKHASH_FIELD_NUMBER;
    hash = (53 * hash) + getParentBlockhash().hashCode();
    hash = (37 * hash) + EXECUTED_TRANSACTION_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExecutedTransactionCount());
    if (getTransactionsCount() > 0) {
      hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionsList().hashCode();
    }
    hash = (37 * hash) + UPDATED_ACCOUNT_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdatedAccountCount());
    if (getAccountsCount() > 0) {
      hash = (37 * hash) + ACCOUNTS_FIELD_NUMBER;
      hash = (53 * hash) + getAccountsList().hashCode();
    }
    hash = (37 * hash) + ENTRIES_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEntriesCount12());
    if (getEntries13Count() > 0) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntries13List().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SubscribeUpdateBlock parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeUpdateBlock parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeUpdateBlock parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeUpdateBlock parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeUpdateBlock parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeUpdateBlock parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeUpdateBlock parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SubscribeUpdateBlock parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SubscribeUpdateBlock parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SubscribeUpdateBlock parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SubscribeUpdateBlock parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SubscribeUpdateBlock parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SubscribeUpdateBlock prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geyser.SubscribeUpdateBlock}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geyser.SubscribeUpdateBlock)
      SubscribeUpdateBlockOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GeyserOuterClass.internal_static_geyser_SubscribeUpdateBlock_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GeyserOuterClass.internal_static_geyser_SubscribeUpdateBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SubscribeUpdateBlock.class, Builder.class);
    }

    // Construct using geyser.SubscribeUpdateBlock.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      slot_ = 0L;

      blockhash_ = "";

      if (rewardsBuilder_ == null) {
        rewards_ = null;
      } else {
        rewards_ = null;
        rewardsBuilder_ = null;
      }
      if (blockTimeBuilder_ == null) {
        blockTime_ = null;
      } else {
        blockTime_ = null;
        blockTimeBuilder_ = null;
      }
      if (blockHeightBuilder_ == null) {
        blockHeight_ = null;
      } else {
        blockHeight_ = null;
        blockHeightBuilder_ = null;
      }
      parentSlot_ = 0L;

      parentBlockhash_ = "";

      executedTransactionCount_ = 0L;

      if (transactionsBuilder_ == null) {
        transactions_ = java.util.Collections.emptyList();
      } else {
        transactions_ = null;
        transactionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      updatedAccountCount_ = 0L;

      if (accountsBuilder_ == null) {
        accounts_ = java.util.Collections.emptyList();
      } else {
        accounts_ = null;
        accountsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      entriesCount12_ = 0L;

      if (entries13Builder_ == null) {
        entries13_ = java.util.Collections.emptyList();
      } else {
        entries13_ = null;
        entries13Builder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GeyserOuterClass.internal_static_geyser_SubscribeUpdateBlock_descriptor;
    }

    @Override
    public SubscribeUpdateBlock getDefaultInstanceForType() {
      return SubscribeUpdateBlock.getDefaultInstance();
    }

    @Override
    public SubscribeUpdateBlock build() {
      SubscribeUpdateBlock result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SubscribeUpdateBlock buildPartial() {
      SubscribeUpdateBlock result = new SubscribeUpdateBlock(this);
      int from_bitField0_ = bitField0_;
      result.slot_ = slot_;
      result.blockhash_ = blockhash_;
      if (rewardsBuilder_ == null) {
        result.rewards_ = rewards_;
      } else {
        result.rewards_ = rewardsBuilder_.build();
      }
      if (blockTimeBuilder_ == null) {
        result.blockTime_ = blockTime_;
      } else {
        result.blockTime_ = blockTimeBuilder_.build();
      }
      if (blockHeightBuilder_ == null) {
        result.blockHeight_ = blockHeight_;
      } else {
        result.blockHeight_ = blockHeightBuilder_.build();
      }
      result.parentSlot_ = parentSlot_;
      result.parentBlockhash_ = parentBlockhash_;
      result.executedTransactionCount_ = executedTransactionCount_;
      if (transactionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.transactions_ = transactions_;
      } else {
        result.transactions_ = transactionsBuilder_.build();
      }
      result.updatedAccountCount_ = updatedAccountCount_;
      if (accountsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          accounts_ = java.util.Collections.unmodifiableList(accounts_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.accounts_ = accounts_;
      } else {
        result.accounts_ = accountsBuilder_.build();
      }
      result.entriesCount12_ = entriesCount12_;
      if (entries13Builder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          entries13_ = java.util.Collections.unmodifiableList(entries13_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.entries13_ = entries13_;
      } else {
        result.entries13_ = entries13Builder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SubscribeUpdateBlock) {
        return mergeFrom((SubscribeUpdateBlock)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SubscribeUpdateBlock other) {
      if (other == SubscribeUpdateBlock.getDefaultInstance()) return this;
      if (other.getSlot() != 0L) {
        setSlot(other.getSlot());
      }
      if (!other.getBlockhash().isEmpty()) {
        blockhash_ = other.blockhash_;
        onChanged();
      }
      if (other.hasRewards()) {
        mergeRewards(other.getRewards());
      }
      if (other.hasBlockTime()) {
        mergeBlockTime(other.getBlockTime());
      }
      if (other.hasBlockHeight()) {
        mergeBlockHeight(other.getBlockHeight());
      }
      if (other.getParentSlot() != 0L) {
        setParentSlot(other.getParentSlot());
      }
      if (!other.getParentBlockhash().isEmpty()) {
        parentBlockhash_ = other.parentBlockhash_;
        onChanged();
      }
      if (other.getExecutedTransactionCount() != 0L) {
        setExecutedTransactionCount(other.getExecutedTransactionCount());
      }
      if (transactionsBuilder_ == null) {
        if (!other.transactions_.isEmpty()) {
          if (transactions_.isEmpty()) {
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTransactionsIsMutable();
            transactions_.addAll(other.transactions_);
          }
          onChanged();
        }
      } else {
        if (!other.transactions_.isEmpty()) {
          if (transactionsBuilder_.isEmpty()) {
            transactionsBuilder_.dispose();
            transactionsBuilder_ = null;
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            transactionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransactionsFieldBuilder() : null;
          } else {
            transactionsBuilder_.addAllMessages(other.transactions_);
          }
        }
      }
      if (other.getUpdatedAccountCount() != 0L) {
        setUpdatedAccountCount(other.getUpdatedAccountCount());
      }
      if (accountsBuilder_ == null) {
        if (!other.accounts_.isEmpty()) {
          if (accounts_.isEmpty()) {
            accounts_ = other.accounts_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAccountsIsMutable();
            accounts_.addAll(other.accounts_);
          }
          onChanged();
        }
      } else {
        if (!other.accounts_.isEmpty()) {
          if (accountsBuilder_.isEmpty()) {
            accountsBuilder_.dispose();
            accountsBuilder_ = null;
            accounts_ = other.accounts_;
            bitField0_ = (bitField0_ & ~0x00000002);
            accountsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAccountsFieldBuilder() : null;
          } else {
            accountsBuilder_.addAllMessages(other.accounts_);
          }
        }
      }
      if (other.getEntriesCount12() != 0L) {
        setEntriesCount12(other.getEntriesCount12());
      }
      if (entries13Builder_ == null) {
        if (!other.entries13_.isEmpty()) {
          if (entries13_.isEmpty()) {
            entries13_ = other.entries13_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureEntries13IsMutable();
            entries13_.addAll(other.entries13_);
          }
          onChanged();
        }
      } else {
        if (!other.entries13_.isEmpty()) {
          if (entries13Builder_.isEmpty()) {
            entries13Builder_.dispose();
            entries13Builder_ = null;
            entries13_ = other.entries13_;
            bitField0_ = (bitField0_ & ~0x00000004);
            entries13Builder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntries13FieldBuilder() : null;
          } else {
            entries13Builder_.addAllMessages(other.entries13_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              slot_ = input.readUInt64();

              break;
            } // case 8
            case 18: {
              blockhash_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getRewardsFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getBlockTimeFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getBlockHeightFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 42
            case 50: {
              SubscribeUpdateTransactionInfo m =
                  input.readMessage(
                      SubscribeUpdateTransactionInfo.parser(),
                      extensionRegistry);
              if (transactionsBuilder_ == null) {
                ensureTransactionsIsMutable();
                transactions_.add(m);
              } else {
                transactionsBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 56: {
              parentSlot_ = input.readUInt64();

              break;
            } // case 56
            case 66: {
              parentBlockhash_ = input.readStringRequireUtf8();

              break;
            } // case 66
            case 72: {
              executedTransactionCount_ = input.readUInt64();

              break;
            } // case 72
            case 80: {
              updatedAccountCount_ = input.readUInt64();

              break;
            } // case 80
            case 90: {
              SubscribeUpdateAccountInfo m =
                  input.readMessage(
                      SubscribeUpdateAccountInfo.parser(),
                      extensionRegistry);
              if (accountsBuilder_ == null) {
                ensureAccountsIsMutable();
                accounts_.add(m);
              } else {
                accountsBuilder_.addMessage(m);
              }
              break;
            } // case 90
            case 96: {
              entriesCount12_ = input.readUInt64();

              break;
            } // case 96
            case 106: {
              SubscribeUpdateEntry m =
                  input.readMessage(
                      SubscribeUpdateEntry.parser(),
                      extensionRegistry);
              if (entries13Builder_ == null) {
                ensureEntries13IsMutable();
                entries13_.add(m);
              } else {
                entries13Builder_.addMessage(m);
              }
              break;
            } // case 106
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long slot_ ;
    /**
     * <code>uint64 slot = 1;</code>
     * @return The slot.
     */
    @Override
    public long getSlot() {
      return slot_;
    }
    /**
     * <code>uint64 slot = 1;</code>
     * @param value The slot to set.
     * @return This builder for chaining.
     */
    public Builder setSlot(long value) {
      
      slot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 slot = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlot() {
      
      slot_ = 0L;
      onChanged();
      return this;
    }

    private Object blockhash_ = "";
    /**
     * <code>string blockhash = 2;</code>
     * @return The blockhash.
     */
    public String getBlockhash() {
      Object ref = blockhash_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blockhash_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string blockhash = 2;</code>
     * @return The bytes for blockhash.
     */
    public com.google.protobuf.ByteString
        getBlockhashBytes() {
      Object ref = blockhash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        blockhash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string blockhash = 2;</code>
     * @param value The blockhash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockhash(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      blockhash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string blockhash = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockhash() {
      
      blockhash_ = getDefaultInstance().getBlockhash();
      onChanged();
      return this;
    }
    /**
     * <code>string blockhash = 2;</code>
     * @param value The bytes for blockhash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockhashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      blockhash_ = value;
      onChanged();
      return this;
    }

    private solana.storage.ConfirmedBlock.Rewards rewards_;
    private com.google.protobuf.SingleFieldBuilderV3<
        solana.storage.ConfirmedBlock.Rewards, solana.storage.ConfirmedBlock.Rewards.Builder, solana.storage.ConfirmedBlock.RewardsOrBuilder> rewardsBuilder_;
    /**
     * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
     * @return Whether the rewards field is set.
     */
    public boolean hasRewards() {
      return rewardsBuilder_ != null || rewards_ != null;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
     * @return The rewards.
     */
    public solana.storage.ConfirmedBlock.Rewards getRewards() {
      if (rewardsBuilder_ == null) {
        return rewards_ == null ? solana.storage.ConfirmedBlock.Rewards.getDefaultInstance() : rewards_;
      } else {
        return rewardsBuilder_.getMessage();
      }
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
     */
    public Builder setRewards(solana.storage.ConfirmedBlock.Rewards value) {
      if (rewardsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rewards_ = value;
        onChanged();
      } else {
        rewardsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
     */
    public Builder setRewards(
        solana.storage.ConfirmedBlock.Rewards.Builder builderForValue) {
      if (rewardsBuilder_ == null) {
        rewards_ = builderForValue.build();
        onChanged();
      } else {
        rewardsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
     */
    public Builder mergeRewards(solana.storage.ConfirmedBlock.Rewards value) {
      if (rewardsBuilder_ == null) {
        if (rewards_ != null) {
          rewards_ =
            solana.storage.ConfirmedBlock.Rewards.newBuilder(rewards_).mergeFrom(value).buildPartial();
        } else {
          rewards_ = value;
        }
        onChanged();
      } else {
        rewardsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
     */
    public Builder clearRewards() {
      if (rewardsBuilder_ == null) {
        rewards_ = null;
        onChanged();
      } else {
        rewards_ = null;
        rewardsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
     */
    public solana.storage.ConfirmedBlock.Rewards.Builder getRewardsBuilder() {
      
      onChanged();
      return getRewardsFieldBuilder().getBuilder();
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
     */
    public solana.storage.ConfirmedBlock.RewardsOrBuilder getRewardsOrBuilder() {
      if (rewardsBuilder_ != null) {
        return rewardsBuilder_.getMessageOrBuilder();
      } else {
        return rewards_ == null ?
            solana.storage.ConfirmedBlock.Rewards.getDefaultInstance() : rewards_;
      }
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.Rewards rewards = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        solana.storage.ConfirmedBlock.Rewards, solana.storage.ConfirmedBlock.Rewards.Builder, solana.storage.ConfirmedBlock.RewardsOrBuilder> 
        getRewardsFieldBuilder() {
      if (rewardsBuilder_ == null) {
        rewardsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            solana.storage.ConfirmedBlock.Rewards, solana.storage.ConfirmedBlock.Rewards.Builder, solana.storage.ConfirmedBlock.RewardsOrBuilder>(
                getRewards(),
                getParentForChildren(),
                isClean());
        rewards_ = null;
      }
      return rewardsBuilder_;
    }

    private solana.storage.ConfirmedBlock.UnixTimestamp blockTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        solana.storage.ConfirmedBlock.UnixTimestamp, solana.storage.ConfirmedBlock.UnixTimestamp.Builder, solana.storage.ConfirmedBlock.UnixTimestampOrBuilder> blockTimeBuilder_;
    /**
     * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
     * @return Whether the blockTime field is set.
     */
    public boolean hasBlockTime() {
      return blockTimeBuilder_ != null || blockTime_ != null;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
     * @return The blockTime.
     */
    public solana.storage.ConfirmedBlock.UnixTimestamp getBlockTime() {
      if (blockTimeBuilder_ == null) {
        return blockTime_ == null ? solana.storage.ConfirmedBlock.UnixTimestamp.getDefaultInstance() : blockTime_;
      } else {
        return blockTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
     */
    public Builder setBlockTime(solana.storage.ConfirmedBlock.UnixTimestamp value) {
      if (blockTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        blockTime_ = value;
        onChanged();
      } else {
        blockTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
     */
    public Builder setBlockTime(
        solana.storage.ConfirmedBlock.UnixTimestamp.Builder builderForValue) {
      if (blockTimeBuilder_ == null) {
        blockTime_ = builderForValue.build();
        onChanged();
      } else {
        blockTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
     */
    public Builder mergeBlockTime(solana.storage.ConfirmedBlock.UnixTimestamp value) {
      if (blockTimeBuilder_ == null) {
        if (blockTime_ != null) {
          blockTime_ =
            solana.storage.ConfirmedBlock.UnixTimestamp.newBuilder(blockTime_).mergeFrom(value).buildPartial();
        } else {
          blockTime_ = value;
        }
        onChanged();
      } else {
        blockTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
     */
    public Builder clearBlockTime() {
      if (blockTimeBuilder_ == null) {
        blockTime_ = null;
        onChanged();
      } else {
        blockTime_ = null;
        blockTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
     */
    public solana.storage.ConfirmedBlock.UnixTimestamp.Builder getBlockTimeBuilder() {
      
      onChanged();
      return getBlockTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
     */
    public solana.storage.ConfirmedBlock.UnixTimestampOrBuilder getBlockTimeOrBuilder() {
      if (blockTimeBuilder_ != null) {
        return blockTimeBuilder_.getMessageOrBuilder();
      } else {
        return blockTime_ == null ?
            solana.storage.ConfirmedBlock.UnixTimestamp.getDefaultInstance() : blockTime_;
      }
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.UnixTimestamp block_time = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        solana.storage.ConfirmedBlock.UnixTimestamp, solana.storage.ConfirmedBlock.UnixTimestamp.Builder, solana.storage.ConfirmedBlock.UnixTimestampOrBuilder> 
        getBlockTimeFieldBuilder() {
      if (blockTimeBuilder_ == null) {
        blockTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            solana.storage.ConfirmedBlock.UnixTimestamp, solana.storage.ConfirmedBlock.UnixTimestamp.Builder, solana.storage.ConfirmedBlock.UnixTimestampOrBuilder>(
                getBlockTime(),
                getParentForChildren(),
                isClean());
        blockTime_ = null;
      }
      return blockTimeBuilder_;
    }

    private solana.storage.ConfirmedBlock.BlockHeight blockHeight_;
    private com.google.protobuf.SingleFieldBuilderV3<
        solana.storage.ConfirmedBlock.BlockHeight, solana.storage.ConfirmedBlock.BlockHeight.Builder, solana.storage.ConfirmedBlock.BlockHeightOrBuilder> blockHeightBuilder_;
    /**
     * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
     * @return Whether the blockHeight field is set.
     */
    public boolean hasBlockHeight() {
      return blockHeightBuilder_ != null || blockHeight_ != null;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
     * @return The blockHeight.
     */
    public solana.storage.ConfirmedBlock.BlockHeight getBlockHeight() {
      if (blockHeightBuilder_ == null) {
        return blockHeight_ == null ? solana.storage.ConfirmedBlock.BlockHeight.getDefaultInstance() : blockHeight_;
      } else {
        return blockHeightBuilder_.getMessage();
      }
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
     */
    public Builder setBlockHeight(solana.storage.ConfirmedBlock.BlockHeight value) {
      if (blockHeightBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        blockHeight_ = value;
        onChanged();
      } else {
        blockHeightBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
     */
    public Builder setBlockHeight(
        solana.storage.ConfirmedBlock.BlockHeight.Builder builderForValue) {
      if (blockHeightBuilder_ == null) {
        blockHeight_ = builderForValue.build();
        onChanged();
      } else {
        blockHeightBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
     */
    public Builder mergeBlockHeight(solana.storage.ConfirmedBlock.BlockHeight value) {
      if (blockHeightBuilder_ == null) {
        if (blockHeight_ != null) {
          blockHeight_ =
            solana.storage.ConfirmedBlock.BlockHeight.newBuilder(blockHeight_).mergeFrom(value).buildPartial();
        } else {
          blockHeight_ = value;
        }
        onChanged();
      } else {
        blockHeightBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
     */
    public Builder clearBlockHeight() {
      if (blockHeightBuilder_ == null) {
        blockHeight_ = null;
        onChanged();
      } else {
        blockHeight_ = null;
        blockHeightBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
     */
    public solana.storage.ConfirmedBlock.BlockHeight.Builder getBlockHeightBuilder() {
      
      onChanged();
      return getBlockHeightFieldBuilder().getBuilder();
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
     */
    public solana.storage.ConfirmedBlock.BlockHeightOrBuilder getBlockHeightOrBuilder() {
      if (blockHeightBuilder_ != null) {
        return blockHeightBuilder_.getMessageOrBuilder();
      } else {
        return blockHeight_ == null ?
            solana.storage.ConfirmedBlock.BlockHeight.getDefaultInstance() : blockHeight_;
      }
    }
    /**
     * <code>.solana.storage.ConfirmedBlock.BlockHeight block_height = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        solana.storage.ConfirmedBlock.BlockHeight, solana.storage.ConfirmedBlock.BlockHeight.Builder, solana.storage.ConfirmedBlock.BlockHeightOrBuilder> 
        getBlockHeightFieldBuilder() {
      if (blockHeightBuilder_ == null) {
        blockHeightBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            solana.storage.ConfirmedBlock.BlockHeight, solana.storage.ConfirmedBlock.BlockHeight.Builder, solana.storage.ConfirmedBlock.BlockHeightOrBuilder>(
                getBlockHeight(),
                getParentForChildren(),
                isClean());
        blockHeight_ = null;
      }
      return blockHeightBuilder_;
    }

    private long parentSlot_ ;
    /**
     * <code>uint64 parent_slot = 7;</code>
     * @return The parentSlot.
     */
    @Override
    public long getParentSlot() {
      return parentSlot_;
    }
    /**
     * <code>uint64 parent_slot = 7;</code>
     * @param value The parentSlot to set.
     * @return This builder for chaining.
     */
    public Builder setParentSlot(long value) {
      
      parentSlot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 parent_slot = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentSlot() {
      
      parentSlot_ = 0L;
      onChanged();
      return this;
    }

    private Object parentBlockhash_ = "";
    /**
     * <code>string parent_blockhash = 8;</code>
     * @return The parentBlockhash.
     */
    public String getParentBlockhash() {
      Object ref = parentBlockhash_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        parentBlockhash_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string parent_blockhash = 8;</code>
     * @return The bytes for parentBlockhash.
     */
    public com.google.protobuf.ByteString
        getParentBlockhashBytes() {
      Object ref = parentBlockhash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        parentBlockhash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parent_blockhash = 8;</code>
     * @param value The parentBlockhash to set.
     * @return This builder for chaining.
     */
    public Builder setParentBlockhash(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      parentBlockhash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string parent_blockhash = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentBlockhash() {
      
      parentBlockhash_ = getDefaultInstance().getParentBlockhash();
      onChanged();
      return this;
    }
    /**
     * <code>string parent_blockhash = 8;</code>
     * @param value The bytes for parentBlockhash to set.
     * @return This builder for chaining.
     */
    public Builder setParentBlockhashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      parentBlockhash_ = value;
      onChanged();
      return this;
    }

    private long executedTransactionCount_ ;
    /**
     * <code>uint64 executed_transaction_count = 9;</code>
     * @return The executedTransactionCount.
     */
    @Override
    public long getExecutedTransactionCount() {
      return executedTransactionCount_;
    }
    /**
     * <code>uint64 executed_transaction_count = 9;</code>
     * @param value The executedTransactionCount to set.
     * @return This builder for chaining.
     */
    public Builder setExecutedTransactionCount(long value) {
      
      executedTransactionCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 executed_transaction_count = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutedTransactionCount() {
      
      executedTransactionCount_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<SubscribeUpdateTransactionInfo> transactions_ =
      java.util.Collections.emptyList();
    private void ensureTransactionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        transactions_ = new java.util.ArrayList<SubscribeUpdateTransactionInfo>(transactions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        SubscribeUpdateTransactionInfo, SubscribeUpdateTransactionInfo.Builder, SubscribeUpdateTransactionInfoOrBuilder> transactionsBuilder_;

    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public java.util.List<SubscribeUpdateTransactionInfo> getTransactionsList() {
      if (transactionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transactions_);
      } else {
        return transactionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public int getTransactionsCount() {
      if (transactionsBuilder_ == null) {
        return transactions_.size();
      } else {
        return transactionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public SubscribeUpdateTransactionInfo getTransactions(int index) {
      if (transactionsBuilder_ == null) {
        return transactions_.get(index);
      } else {
        return transactionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public Builder setTransactions(
        int index, SubscribeUpdateTransactionInfo value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.set(index, value);
        onChanged();
      } else {
        transactionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public Builder setTransactions(
        int index, SubscribeUpdateTransactionInfo.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.set(index, builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public Builder addTransactions(SubscribeUpdateTransactionInfo value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.add(value);
        onChanged();
      } else {
        transactionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public Builder addTransactions(
        int index, SubscribeUpdateTransactionInfo value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.add(index, value);
        onChanged();
      } else {
        transactionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public Builder addTransactions(
        SubscribeUpdateTransactionInfo.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.add(builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public Builder addTransactions(
        int index, SubscribeUpdateTransactionInfo.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.add(index, builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public Builder addAllTransactions(
        Iterable<? extends SubscribeUpdateTransactionInfo> values) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactions_);
        onChanged();
      } else {
        transactionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public Builder clearTransactions() {
      if (transactionsBuilder_ == null) {
        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        transactionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public Builder removeTransactions(int index) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.remove(index);
        onChanged();
      } else {
        transactionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public SubscribeUpdateTransactionInfo.Builder getTransactionsBuilder(
        int index) {
      return getTransactionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public SubscribeUpdateTransactionInfoOrBuilder getTransactionsOrBuilder(
        int index) {
      if (transactionsBuilder_ == null) {
        return transactions_.get(index);  } else {
        return transactionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public java.util.List<? extends SubscribeUpdateTransactionInfoOrBuilder>
         getTransactionsOrBuilderList() {
      if (transactionsBuilder_ != null) {
        return transactionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transactions_);
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public SubscribeUpdateTransactionInfo.Builder addTransactionsBuilder() {
      return getTransactionsFieldBuilder().addBuilder(
          SubscribeUpdateTransactionInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public SubscribeUpdateTransactionInfo.Builder addTransactionsBuilder(
        int index) {
      return getTransactionsFieldBuilder().addBuilder(
          index, SubscribeUpdateTransactionInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateTransactionInfo transactions = 6;</code>
     */
    public java.util.List<SubscribeUpdateTransactionInfo.Builder>
         getTransactionsBuilderList() {
      return getTransactionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        SubscribeUpdateTransactionInfo, SubscribeUpdateTransactionInfo.Builder, SubscribeUpdateTransactionInfoOrBuilder>
        getTransactionsFieldBuilder() {
      if (transactionsBuilder_ == null) {
        transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            SubscribeUpdateTransactionInfo, SubscribeUpdateTransactionInfo.Builder, SubscribeUpdateTransactionInfoOrBuilder>(
                transactions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        transactions_ = null;
      }
      return transactionsBuilder_;
    }

    private long updatedAccountCount_ ;
    /**
     * <code>uint64 updated_account_count = 10;</code>
     * @return The updatedAccountCount.
     */
    @Override
    public long getUpdatedAccountCount() {
      return updatedAccountCount_;
    }
    /**
     * <code>uint64 updated_account_count = 10;</code>
     * @param value The updatedAccountCount to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAccountCount(long value) {
      
      updatedAccountCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 updated_account_count = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAccountCount() {
      
      updatedAccountCount_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<SubscribeUpdateAccountInfo> accounts_ =
      java.util.Collections.emptyList();
    private void ensureAccountsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        accounts_ = new java.util.ArrayList<SubscribeUpdateAccountInfo>(accounts_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        SubscribeUpdateAccountInfo, SubscribeUpdateAccountInfo.Builder, SubscribeUpdateAccountInfoOrBuilder> accountsBuilder_;

    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public java.util.List<SubscribeUpdateAccountInfo> getAccountsList() {
      if (accountsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(accounts_);
      } else {
        return accountsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public int getAccountsCount() {
      if (accountsBuilder_ == null) {
        return accounts_.size();
      } else {
        return accountsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public SubscribeUpdateAccountInfo getAccounts(int index) {
      if (accountsBuilder_ == null) {
        return accounts_.get(index);
      } else {
        return accountsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public Builder setAccounts(
        int index, SubscribeUpdateAccountInfo value) {
      if (accountsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountsIsMutable();
        accounts_.set(index, value);
        onChanged();
      } else {
        accountsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public Builder setAccounts(
        int index, SubscribeUpdateAccountInfo.Builder builderForValue) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.set(index, builderForValue.build());
        onChanged();
      } else {
        accountsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public Builder addAccounts(SubscribeUpdateAccountInfo value) {
      if (accountsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountsIsMutable();
        accounts_.add(value);
        onChanged();
      } else {
        accountsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public Builder addAccounts(
        int index, SubscribeUpdateAccountInfo value) {
      if (accountsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountsIsMutable();
        accounts_.add(index, value);
        onChanged();
      } else {
        accountsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public Builder addAccounts(
        SubscribeUpdateAccountInfo.Builder builderForValue) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.add(builderForValue.build());
        onChanged();
      } else {
        accountsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public Builder addAccounts(
        int index, SubscribeUpdateAccountInfo.Builder builderForValue) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.add(index, builderForValue.build());
        onChanged();
      } else {
        accountsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public Builder addAllAccounts(
        Iterable<? extends SubscribeUpdateAccountInfo> values) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, accounts_);
        onChanged();
      } else {
        accountsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public Builder clearAccounts() {
      if (accountsBuilder_ == null) {
        accounts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        accountsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public Builder removeAccounts(int index) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.remove(index);
        onChanged();
      } else {
        accountsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public SubscribeUpdateAccountInfo.Builder getAccountsBuilder(
        int index) {
      return getAccountsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public SubscribeUpdateAccountInfoOrBuilder getAccountsOrBuilder(
        int index) {
      if (accountsBuilder_ == null) {
        return accounts_.get(index);  } else {
        return accountsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public java.util.List<? extends SubscribeUpdateAccountInfoOrBuilder>
         getAccountsOrBuilderList() {
      if (accountsBuilder_ != null) {
        return accountsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(accounts_);
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public SubscribeUpdateAccountInfo.Builder addAccountsBuilder() {
      return getAccountsFieldBuilder().addBuilder(
          SubscribeUpdateAccountInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public SubscribeUpdateAccountInfo.Builder addAccountsBuilder(
        int index) {
      return getAccountsFieldBuilder().addBuilder(
          index, SubscribeUpdateAccountInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateAccountInfo accounts = 11;</code>
     */
    public java.util.List<SubscribeUpdateAccountInfo.Builder>
         getAccountsBuilderList() {
      return getAccountsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        SubscribeUpdateAccountInfo, SubscribeUpdateAccountInfo.Builder, SubscribeUpdateAccountInfoOrBuilder>
        getAccountsFieldBuilder() {
      if (accountsBuilder_ == null) {
        accountsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            SubscribeUpdateAccountInfo, SubscribeUpdateAccountInfo.Builder, SubscribeUpdateAccountInfoOrBuilder>(
                accounts_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        accounts_ = null;
      }
      return accountsBuilder_;
    }

    private long entriesCount12_ ;
    /**
     * <code>uint64 entries_count = 12;</code>
     * @return The entriesCount.
     */
    @Override
    public long getEntriesCount12() {
      return entriesCount12_;
    }
    /**
     * <code>uint64 entries_count = 12;</code>
     * @param value The entriesCount to set.
     * @return This builder for chaining.
     */
    public Builder setEntriesCount12(long value) {
      
      entriesCount12_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 entries_count = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntriesCount12() {
      
      entriesCount12_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<SubscribeUpdateEntry> entries13_ =
      java.util.Collections.emptyList();
    private void ensureEntries13IsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        entries13_ = new java.util.ArrayList<SubscribeUpdateEntry>(entries13_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        SubscribeUpdateEntry, SubscribeUpdateEntry.Builder, SubscribeUpdateEntryOrBuilder> entries13Builder_;

    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public java.util.List<SubscribeUpdateEntry> getEntries13List() {
      if (entries13Builder_ == null) {
        return java.util.Collections.unmodifiableList(entries13_);
      } else {
        return entries13Builder_.getMessageList();
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public int getEntries13Count() {
      if (entries13Builder_ == null) {
        return entries13_.size();
      } else {
        return entries13Builder_.getCount();
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public SubscribeUpdateEntry getEntries13(int index) {
      if (entries13Builder_ == null) {
        return entries13_.get(index);
      } else {
        return entries13Builder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public Builder setEntries13(
        int index, SubscribeUpdateEntry value) {
      if (entries13Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntries13IsMutable();
        entries13_.set(index, value);
        onChanged();
      } else {
        entries13Builder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public Builder setEntries13(
        int index, SubscribeUpdateEntry.Builder builderForValue) {
      if (entries13Builder_ == null) {
        ensureEntries13IsMutable();
        entries13_.set(index, builderForValue.build());
        onChanged();
      } else {
        entries13Builder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public Builder addEntries13(SubscribeUpdateEntry value) {
      if (entries13Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntries13IsMutable();
        entries13_.add(value);
        onChanged();
      } else {
        entries13Builder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public Builder addEntries13(
        int index, SubscribeUpdateEntry value) {
      if (entries13Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntries13IsMutable();
        entries13_.add(index, value);
        onChanged();
      } else {
        entries13Builder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public Builder addEntries13(
        SubscribeUpdateEntry.Builder builderForValue) {
      if (entries13Builder_ == null) {
        ensureEntries13IsMutable();
        entries13_.add(builderForValue.build());
        onChanged();
      } else {
        entries13Builder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public Builder addEntries13(
        int index, SubscribeUpdateEntry.Builder builderForValue) {
      if (entries13Builder_ == null) {
        ensureEntries13IsMutable();
        entries13_.add(index, builderForValue.build());
        onChanged();
      } else {
        entries13Builder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public Builder addAllEntries13(
        Iterable<? extends SubscribeUpdateEntry> values) {
      if (entries13Builder_ == null) {
        ensureEntries13IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entries13_);
        onChanged();
      } else {
        entries13Builder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public Builder clearEntries13() {
      if (entries13Builder_ == null) {
        entries13_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        entries13Builder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public Builder removeEntries13(int index) {
      if (entries13Builder_ == null) {
        ensureEntries13IsMutable();
        entries13_.remove(index);
        onChanged();
      } else {
        entries13Builder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public SubscribeUpdateEntry.Builder getEntries13Builder(
        int index) {
      return getEntries13FieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public SubscribeUpdateEntryOrBuilder getEntries13OrBuilder(
        int index) {
      if (entries13Builder_ == null) {
        return entries13_.get(index);  } else {
        return entries13Builder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public java.util.List<? extends SubscribeUpdateEntryOrBuilder>
         getEntries13OrBuilderList() {
      if (entries13Builder_ != null) {
        return entries13Builder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entries13_);
      }
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public SubscribeUpdateEntry.Builder addEntries13Builder() {
      return getEntries13FieldBuilder().addBuilder(
          SubscribeUpdateEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public SubscribeUpdateEntry.Builder addEntries13Builder(
        int index) {
      return getEntries13FieldBuilder().addBuilder(
          index, SubscribeUpdateEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .geyser.SubscribeUpdateEntry entries = 13;</code>
     */
    public java.util.List<SubscribeUpdateEntry.Builder>
         getEntries13BuilderList() {
      return getEntries13FieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        SubscribeUpdateEntry, SubscribeUpdateEntry.Builder, SubscribeUpdateEntryOrBuilder>
        getEntries13FieldBuilder() {
      if (entries13Builder_ == null) {
        entries13Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            SubscribeUpdateEntry, SubscribeUpdateEntry.Builder, SubscribeUpdateEntryOrBuilder>(
                entries13_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        entries13_ = null;
      }
      return entries13Builder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geyser.SubscribeUpdateBlock)
  }

  // @@protoc_insertion_point(class_scope:geyser.SubscribeUpdateBlock)
  private static final SubscribeUpdateBlock DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SubscribeUpdateBlock();
  }

  public static SubscribeUpdateBlock getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscribeUpdateBlock>
      PARSER = new com.google.protobuf.AbstractParser<SubscribeUpdateBlock>() {
    @Override
    public SubscribeUpdateBlock parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubscribeUpdateBlock> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SubscribeUpdateBlock> getParserForType() {
    return PARSER;
  }

  @Override
  public SubscribeUpdateBlock getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

