// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public interface SubscribeUpdatePingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geyser.SubscribeUpdatePing)
    com.google.protobuf.MessageOrBuilder {
}
