// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

/**
 * Protobuf type {@code geyser.SubscribeRequestFilterAccountsFilter}
 */
public final class SubscribeRequestFilterAccountsFilter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geyser.SubscribeRequestFilterAccountsFilter)
    SubscribeRequestFilterAccountsFilterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubscribeRequestFilterAccountsFilter.newBuilder() to construct.
  private SubscribeRequestFilterAccountsFilter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubscribeRequestFilterAccountsFilter() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubscribeRequestFilterAccountsFilter();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GeyserOuterClass.internal_static_geyser_SubscribeRequestFilterAccountsFilter_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GeyserOuterClass.internal_static_geyser_SubscribeRequestFilterAccountsFilter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SubscribeRequestFilterAccountsFilter.class, Builder.class);
  }

  private int filterCase_ = 0;
  private Object filter_;
  public enum FilterCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    MEMCMP(1),
    DATASIZE(2),
    TOKEN_ACCOUNT_STATE(3),
    LAMPORTS(4),
    FILTER_NOT_SET(0);
    private final int value;
    private FilterCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static FilterCase valueOf(int value) {
      return forNumber(value);
    }

    public static FilterCase forNumber(int value) {
      switch (value) {
        case 1: return MEMCMP;
        case 2: return DATASIZE;
        case 3: return TOKEN_ACCOUNT_STATE;
        case 4: return LAMPORTS;
        case 0: return FILTER_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public FilterCase
  getFilterCase() {
    return FilterCase.forNumber(
        filterCase_);
  }

  public static final int MEMCMP_FIELD_NUMBER = 1;
  /**
   * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
   * @return Whether the memcmp field is set.
   */
  @Override
  public boolean hasMemcmp() {
    return filterCase_ == 1;
  }
  /**
   * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
   * @return The memcmp.
   */
  @Override
  public SubscribeRequestFilterAccountsFilterMemcmp getMemcmp() {
    if (filterCase_ == 1) {
       return (SubscribeRequestFilterAccountsFilterMemcmp) filter_;
    }
    return SubscribeRequestFilterAccountsFilterMemcmp.getDefaultInstance();
  }
  /**
   * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
   */
  @Override
  public SubscribeRequestFilterAccountsFilterMemcmpOrBuilder getMemcmpOrBuilder() {
    if (filterCase_ == 1) {
       return (SubscribeRequestFilterAccountsFilterMemcmp) filter_;
    }
    return SubscribeRequestFilterAccountsFilterMemcmp.getDefaultInstance();
  }

  public static final int DATASIZE_FIELD_NUMBER = 2;
  /**
   * <code>uint64 datasize = 2;</code>
   * @return Whether the datasize field is set.
   */
  @Override
  public boolean hasDatasize() {
    return filterCase_ == 2;
  }
  /**
   * <code>uint64 datasize = 2;</code>
   * @return The datasize.
   */
  @Override
  public long getDatasize() {
    if (filterCase_ == 2) {
      return (Long) filter_;
    }
    return 0L;
  }

  public static final int TOKEN_ACCOUNT_STATE_FIELD_NUMBER = 3;
  /**
   * <code>bool token_account_state = 3;</code>
   * @return Whether the tokenAccountState field is set.
   */
  @Override
  public boolean hasTokenAccountState() {
    return filterCase_ == 3;
  }
  /**
   * <code>bool token_account_state = 3;</code>
   * @return The tokenAccountState.
   */
  @Override
  public boolean getTokenAccountState() {
    if (filterCase_ == 3) {
      return (Boolean) filter_;
    }
    return false;
  }

  public static final int LAMPORTS_FIELD_NUMBER = 4;
  /**
   * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
   * @return Whether the lamports field is set.
   */
  @Override
  public boolean hasLamports() {
    return filterCase_ == 4;
  }
  /**
   * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
   * @return The lamports.
   */
  @Override
  public SubscribeRequestFilterAccountsFilterLamports getLamports() {
    if (filterCase_ == 4) {
       return (SubscribeRequestFilterAccountsFilterLamports) filter_;
    }
    return SubscribeRequestFilterAccountsFilterLamports.getDefaultInstance();
  }
  /**
   * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
   */
  @Override
  public SubscribeRequestFilterAccountsFilterLamportsOrBuilder getLamportsOrBuilder() {
    if (filterCase_ == 4) {
       return (SubscribeRequestFilterAccountsFilterLamports) filter_;
    }
    return SubscribeRequestFilterAccountsFilterLamports.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (filterCase_ == 1) {
      output.writeMessage(1, (SubscribeRequestFilterAccountsFilterMemcmp) filter_);
    }
    if (filterCase_ == 2) {
      output.writeUInt64(
          2, (long)((Long) filter_));
    }
    if (filterCase_ == 3) {
      output.writeBool(
          3, (boolean)((Boolean) filter_));
    }
    if (filterCase_ == 4) {
      output.writeMessage(4, (SubscribeRequestFilterAccountsFilterLamports) filter_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (filterCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (SubscribeRequestFilterAccountsFilterMemcmp) filter_);
    }
    if (filterCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(
            2, (long)((Long) filter_));
    }
    if (filterCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            3, (boolean)((Boolean) filter_));
    }
    if (filterCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (SubscribeRequestFilterAccountsFilterLamports) filter_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SubscribeRequestFilterAccountsFilter)) {
      return super.equals(obj);
    }
    SubscribeRequestFilterAccountsFilter other = (SubscribeRequestFilterAccountsFilter) obj;

    if (!getFilterCase().equals(other.getFilterCase())) return false;
    switch (filterCase_) {
      case 1:
        if (!getMemcmp()
            .equals(other.getMemcmp())) return false;
        break;
      case 2:
        if (getDatasize()
            != other.getDatasize()) return false;
        break;
      case 3:
        if (getTokenAccountState()
            != other.getTokenAccountState()) return false;
        break;
      case 4:
        if (!getLamports()
            .equals(other.getLamports())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (filterCase_) {
      case 1:
        hash = (37 * hash) + MEMCMP_FIELD_NUMBER;
        hash = (53 * hash) + getMemcmp().hashCode();
        break;
      case 2:
        hash = (37 * hash) + DATASIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDatasize());
        break;
      case 3:
        hash = (37 * hash) + TOKEN_ACCOUNT_STATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getTokenAccountState());
        break;
      case 4:
        hash = (37 * hash) + LAMPORTS_FIELD_NUMBER;
        hash = (53 * hash) + getLamports().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SubscribeRequestFilterAccountsFilter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeRequestFilterAccountsFilter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeRequestFilterAccountsFilter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeRequestFilterAccountsFilter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeRequestFilterAccountsFilter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeRequestFilterAccountsFilter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeRequestFilterAccountsFilter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SubscribeRequestFilterAccountsFilter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SubscribeRequestFilterAccountsFilter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SubscribeRequestFilterAccountsFilter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SubscribeRequestFilterAccountsFilter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SubscribeRequestFilterAccountsFilter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SubscribeRequestFilterAccountsFilter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geyser.SubscribeRequestFilterAccountsFilter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geyser.SubscribeRequestFilterAccountsFilter)
      SubscribeRequestFilterAccountsFilterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GeyserOuterClass.internal_static_geyser_SubscribeRequestFilterAccountsFilter_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GeyserOuterClass.internal_static_geyser_SubscribeRequestFilterAccountsFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SubscribeRequestFilterAccountsFilter.class, Builder.class);
    }

    // Construct using geyser.SubscribeRequestFilterAccountsFilter.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      if (memcmpBuilder_ != null) {
        memcmpBuilder_.clear();
      }
      if (lamportsBuilder_ != null) {
        lamportsBuilder_.clear();
      }
      filterCase_ = 0;
      filter_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GeyserOuterClass.internal_static_geyser_SubscribeRequestFilterAccountsFilter_descriptor;
    }

    @Override
    public SubscribeRequestFilterAccountsFilter getDefaultInstanceForType() {
      return SubscribeRequestFilterAccountsFilter.getDefaultInstance();
    }

    @Override
    public SubscribeRequestFilterAccountsFilter build() {
      SubscribeRequestFilterAccountsFilter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SubscribeRequestFilterAccountsFilter buildPartial() {
      SubscribeRequestFilterAccountsFilter result = new SubscribeRequestFilterAccountsFilter(this);
      if (filterCase_ == 1) {
        if (memcmpBuilder_ == null) {
          result.filter_ = filter_;
        } else {
          result.filter_ = memcmpBuilder_.build();
        }
      }
      if (filterCase_ == 2) {
        result.filter_ = filter_;
      }
      if (filterCase_ == 3) {
        result.filter_ = filter_;
      }
      if (filterCase_ == 4) {
        if (lamportsBuilder_ == null) {
          result.filter_ = filter_;
        } else {
          result.filter_ = lamportsBuilder_.build();
        }
      }
      result.filterCase_ = filterCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SubscribeRequestFilterAccountsFilter) {
        return mergeFrom((SubscribeRequestFilterAccountsFilter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SubscribeRequestFilterAccountsFilter other) {
      if (other == SubscribeRequestFilterAccountsFilter.getDefaultInstance()) return this;
      switch (other.getFilterCase()) {
        case MEMCMP: {
          mergeMemcmp(other.getMemcmp());
          break;
        }
        case DATASIZE: {
          setDatasize(other.getDatasize());
          break;
        }
        case TOKEN_ACCOUNT_STATE: {
          setTokenAccountState(other.getTokenAccountState());
          break;
        }
        case LAMPORTS: {
          mergeLamports(other.getLamports());
          break;
        }
        case FILTER_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMemcmpFieldBuilder().getBuilder(),
                  extensionRegistry);
              filterCase_ = 1;
              break;
            } // case 10
            case 16: {
              filter_ = input.readUInt64();
              filterCase_ = 2;
              break;
            } // case 16
            case 24: {
              filter_ = input.readBool();
              filterCase_ = 3;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getLamportsFieldBuilder().getBuilder(),
                  extensionRegistry);
              filterCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int filterCase_ = 0;
    private Object filter_;
    public FilterCase
        getFilterCase() {
      return FilterCase.forNumber(
          filterCase_);
    }

    public Builder clearFilter() {
      filterCase_ = 0;
      filter_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        SubscribeRequestFilterAccountsFilterMemcmp, SubscribeRequestFilterAccountsFilterMemcmp.Builder, SubscribeRequestFilterAccountsFilterMemcmpOrBuilder> memcmpBuilder_;
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
     * @return Whether the memcmp field is set.
     */
    @Override
    public boolean hasMemcmp() {
      return filterCase_ == 1;
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
     * @return The memcmp.
     */
    @Override
    public SubscribeRequestFilterAccountsFilterMemcmp getMemcmp() {
      if (memcmpBuilder_ == null) {
        if (filterCase_ == 1) {
          return (SubscribeRequestFilterAccountsFilterMemcmp) filter_;
        }
        return SubscribeRequestFilterAccountsFilterMemcmp.getDefaultInstance();
      } else {
        if (filterCase_ == 1) {
          return memcmpBuilder_.getMessage();
        }
        return SubscribeRequestFilterAccountsFilterMemcmp.getDefaultInstance();
      }
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
     */
    public Builder setMemcmp(SubscribeRequestFilterAccountsFilterMemcmp value) {
      if (memcmpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
        onChanged();
      } else {
        memcmpBuilder_.setMessage(value);
      }
      filterCase_ = 1;
      return this;
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
     */
    public Builder setMemcmp(
        SubscribeRequestFilterAccountsFilterMemcmp.Builder builderForValue) {
      if (memcmpBuilder_ == null) {
        filter_ = builderForValue.build();
        onChanged();
      } else {
        memcmpBuilder_.setMessage(builderForValue.build());
      }
      filterCase_ = 1;
      return this;
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
     */
    public Builder mergeMemcmp(SubscribeRequestFilterAccountsFilterMemcmp value) {
      if (memcmpBuilder_ == null) {
        if (filterCase_ == 1 &&
            filter_ != SubscribeRequestFilterAccountsFilterMemcmp.getDefaultInstance()) {
          filter_ = SubscribeRequestFilterAccountsFilterMemcmp.newBuilder((SubscribeRequestFilterAccountsFilterMemcmp) filter_)
              .mergeFrom(value).buildPartial();
        } else {
          filter_ = value;
        }
        onChanged();
      } else {
        if (filterCase_ == 1) {
          memcmpBuilder_.mergeFrom(value);
        } else {
          memcmpBuilder_.setMessage(value);
        }
      }
      filterCase_ = 1;
      return this;
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
     */
    public Builder clearMemcmp() {
      if (memcmpBuilder_ == null) {
        if (filterCase_ == 1) {
          filterCase_ = 0;
          filter_ = null;
          onChanged();
        }
      } else {
        if (filterCase_ == 1) {
          filterCase_ = 0;
          filter_ = null;
        }
        memcmpBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
     */
    public SubscribeRequestFilterAccountsFilterMemcmp.Builder getMemcmpBuilder() {
      return getMemcmpFieldBuilder().getBuilder();
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
     */
    @Override
    public SubscribeRequestFilterAccountsFilterMemcmpOrBuilder getMemcmpOrBuilder() {
      if ((filterCase_ == 1) && (memcmpBuilder_ != null)) {
        return memcmpBuilder_.getMessageOrBuilder();
      } else {
        if (filterCase_ == 1) {
          return (SubscribeRequestFilterAccountsFilterMemcmp) filter_;
        }
        return SubscribeRequestFilterAccountsFilterMemcmp.getDefaultInstance();
      }
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterMemcmp memcmp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        SubscribeRequestFilterAccountsFilterMemcmp, SubscribeRequestFilterAccountsFilterMemcmp.Builder, SubscribeRequestFilterAccountsFilterMemcmpOrBuilder>
        getMemcmpFieldBuilder() {
      if (memcmpBuilder_ == null) {
        if (!(filterCase_ == 1)) {
          filter_ = SubscribeRequestFilterAccountsFilterMemcmp.getDefaultInstance();
        }
        memcmpBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            SubscribeRequestFilterAccountsFilterMemcmp, SubscribeRequestFilterAccountsFilterMemcmp.Builder, SubscribeRequestFilterAccountsFilterMemcmpOrBuilder>(
                (SubscribeRequestFilterAccountsFilterMemcmp) filter_,
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      filterCase_ = 1;
      onChanged();;
      return memcmpBuilder_;
    }

    /**
     * <code>uint64 datasize = 2;</code>
     * @return Whether the datasize field is set.
     */
    public boolean hasDatasize() {
      return filterCase_ == 2;
    }
    /**
     * <code>uint64 datasize = 2;</code>
     * @return The datasize.
     */
    public long getDatasize() {
      if (filterCase_ == 2) {
        return (Long) filter_;
      }
      return 0L;
    }
    /**
     * <code>uint64 datasize = 2;</code>
     * @param value The datasize to set.
     * @return This builder for chaining.
     */
    public Builder setDatasize(long value) {
      filterCase_ = 2;
      filter_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 datasize = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDatasize() {
      if (filterCase_ == 2) {
        filterCase_ = 0;
        filter_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool token_account_state = 3;</code>
     * @return Whether the tokenAccountState field is set.
     */
    public boolean hasTokenAccountState() {
      return filterCase_ == 3;
    }
    /**
     * <code>bool token_account_state = 3;</code>
     * @return The tokenAccountState.
     */
    public boolean getTokenAccountState() {
      if (filterCase_ == 3) {
        return (Boolean) filter_;
      }
      return false;
    }
    /**
     * <code>bool token_account_state = 3;</code>
     * @param value The tokenAccountState to set.
     * @return This builder for chaining.
     */
    public Builder setTokenAccountState(boolean value) {
      filterCase_ = 3;
      filter_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool token_account_state = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenAccountState() {
      if (filterCase_ == 3) {
        filterCase_ = 0;
        filter_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        SubscribeRequestFilterAccountsFilterLamports, SubscribeRequestFilterAccountsFilterLamports.Builder, SubscribeRequestFilterAccountsFilterLamportsOrBuilder> lamportsBuilder_;
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
     * @return Whether the lamports field is set.
     */
    @Override
    public boolean hasLamports() {
      return filterCase_ == 4;
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
     * @return The lamports.
     */
    @Override
    public SubscribeRequestFilterAccountsFilterLamports getLamports() {
      if (lamportsBuilder_ == null) {
        if (filterCase_ == 4) {
          return (SubscribeRequestFilterAccountsFilterLamports) filter_;
        }
        return SubscribeRequestFilterAccountsFilterLamports.getDefaultInstance();
      } else {
        if (filterCase_ == 4) {
          return lamportsBuilder_.getMessage();
        }
        return SubscribeRequestFilterAccountsFilterLamports.getDefaultInstance();
      }
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
     */
    public Builder setLamports(SubscribeRequestFilterAccountsFilterLamports value) {
      if (lamportsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
        onChanged();
      } else {
        lamportsBuilder_.setMessage(value);
      }
      filterCase_ = 4;
      return this;
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
     */
    public Builder setLamports(
        SubscribeRequestFilterAccountsFilterLamports.Builder builderForValue) {
      if (lamportsBuilder_ == null) {
        filter_ = builderForValue.build();
        onChanged();
      } else {
        lamportsBuilder_.setMessage(builderForValue.build());
      }
      filterCase_ = 4;
      return this;
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
     */
    public Builder mergeLamports(SubscribeRequestFilterAccountsFilterLamports value) {
      if (lamportsBuilder_ == null) {
        if (filterCase_ == 4 &&
            filter_ != SubscribeRequestFilterAccountsFilterLamports.getDefaultInstance()) {
          filter_ = SubscribeRequestFilterAccountsFilterLamports.newBuilder((SubscribeRequestFilterAccountsFilterLamports) filter_)
              .mergeFrom(value).buildPartial();
        } else {
          filter_ = value;
        }
        onChanged();
      } else {
        if (filterCase_ == 4) {
          lamportsBuilder_.mergeFrom(value);
        } else {
          lamportsBuilder_.setMessage(value);
        }
      }
      filterCase_ = 4;
      return this;
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
     */
    public Builder clearLamports() {
      if (lamportsBuilder_ == null) {
        if (filterCase_ == 4) {
          filterCase_ = 0;
          filter_ = null;
          onChanged();
        }
      } else {
        if (filterCase_ == 4) {
          filterCase_ = 0;
          filter_ = null;
        }
        lamportsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
     */
    public SubscribeRequestFilterAccountsFilterLamports.Builder getLamportsBuilder() {
      return getLamportsFieldBuilder().getBuilder();
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
     */
    @Override
    public SubscribeRequestFilterAccountsFilterLamportsOrBuilder getLamportsOrBuilder() {
      if ((filterCase_ == 4) && (lamportsBuilder_ != null)) {
        return lamportsBuilder_.getMessageOrBuilder();
      } else {
        if (filterCase_ == 4) {
          return (SubscribeRequestFilterAccountsFilterLamports) filter_;
        }
        return SubscribeRequestFilterAccountsFilterLamports.getDefaultInstance();
      }
    }
    /**
     * <code>.geyser.SubscribeRequestFilterAccountsFilterLamports lamports = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        SubscribeRequestFilterAccountsFilterLamports, SubscribeRequestFilterAccountsFilterLamports.Builder, SubscribeRequestFilterAccountsFilterLamportsOrBuilder>
        getLamportsFieldBuilder() {
      if (lamportsBuilder_ == null) {
        if (!(filterCase_ == 4)) {
          filter_ = SubscribeRequestFilterAccountsFilterLamports.getDefaultInstance();
        }
        lamportsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            SubscribeRequestFilterAccountsFilterLamports, SubscribeRequestFilterAccountsFilterLamports.Builder, SubscribeRequestFilterAccountsFilterLamportsOrBuilder>(
                (SubscribeRequestFilterAccountsFilterLamports) filter_,
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      filterCase_ = 4;
      onChanged();;
      return lamportsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geyser.SubscribeRequestFilterAccountsFilter)
  }

  // @@protoc_insertion_point(class_scope:geyser.SubscribeRequestFilterAccountsFilter)
  private static final SubscribeRequestFilterAccountsFilter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SubscribeRequestFilterAccountsFilter();
  }

  public static SubscribeRequestFilterAccountsFilter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscribeRequestFilterAccountsFilter>
      PARSER = new com.google.protobuf.AbstractParser<SubscribeRequestFilterAccountsFilter>() {
    @Override
    public SubscribeRequestFilterAccountsFilter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubscribeRequestFilterAccountsFilter> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SubscribeRequestFilterAccountsFilter> getParserForType() {
    return PARSER;
  }

  @Override
  public SubscribeRequestFilterAccountsFilter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

