// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public interface SubscribeRequestFilterBlocksOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geyser.SubscribeRequestFilterBlocks)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string account_include = 1;</code>
   * @return A list containing the accountInclude.
   */
  java.util.List<String>
      getAccountIncludeList();
  /**
   * <code>repeated string account_include = 1;</code>
   * @return The count of accountInclude.
   */
  int getAccountIncludeCount();
  /**
   * <code>repeated string account_include = 1;</code>
   * @param index The index of the element to return.
   * @return The accountInclude at the given index.
   */
  String getAccountInclude(int index);
  /**
   * <code>repeated string account_include = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the accountInclude at the given index.
   */
  com.google.protobuf.ByteString
      getAccountIncludeBytes(int index);

  /**
   * <code>optional bool include_transactions = 2;</code>
   * @return Whether the includeTransactions field is set.
   */
  boolean hasIncludeTransactions();
  /**
   * <code>optional bool include_transactions = 2;</code>
   * @return The includeTransactions.
   */
  boolean getIncludeTransactions();

  /**
   * <code>optional bool include_accounts = 3;</code>
   * @return Whether the includeAccounts field is set.
   */
  boolean hasIncludeAccounts();
  /**
   * <code>optional bool include_accounts = 3;</code>
   * @return The includeAccounts.
   */
  boolean getIncludeAccounts();

  /**
   * <code>optional bool include_entries = 4;</code>
   * @return Whether the includeEntries field is set.
   */
  boolean hasIncludeEntries();
  /**
   * <code>optional bool include_entries = 4;</code>
   * @return The includeEntries.
   */
  boolean getIncludeEntries();
}
