// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

/**
 * Protobuf type {@code geyser.SubscribeRequestFilterTransactions}
 */
public final class SubscribeRequestFilterTransactions extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geyser.SubscribeRequestFilterTransactions)
    SubscribeRequestFilterTransactionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubscribeRequestFilterTransactions.newBuilder() to construct.
  private SubscribeRequestFilterTransactions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubscribeRequestFilterTransactions() {
    signature_ = "";
    accountInclude_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    accountExclude_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    accountRequired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubscribeRequestFilterTransactions();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GeyserOuterClass.internal_static_geyser_SubscribeRequestFilterTransactions_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GeyserOuterClass.internal_static_geyser_SubscribeRequestFilterTransactions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SubscribeRequestFilterTransactions.class, Builder.class);
  }

  private int bitField0_;
  public static final int VOTE_FIELD_NUMBER = 1;
  private boolean vote_;
  /**
   * <code>optional bool vote = 1;</code>
   * @return Whether the vote field is set.
   */
  @Override
  public boolean hasVote() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bool vote = 1;</code>
   * @return The vote.
   */
  @Override
  public boolean getVote() {
    return vote_;
  }

  public static final int FAILED_FIELD_NUMBER = 2;
  private boolean failed_;
  /**
   * <code>optional bool failed = 2;</code>
   * @return Whether the failed field is set.
   */
  @Override
  public boolean hasFailed() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bool failed = 2;</code>
   * @return The failed.
   */
  @Override
  public boolean getFailed() {
    return failed_;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 5;
  private volatile Object signature_;
  /**
   * <code>optional string signature = 5;</code>
   * @return Whether the signature field is set.
   */
  @Override
  public boolean hasSignature() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string signature = 5;</code>
   * @return The signature.
   */
  @Override
  public String getSignature() {
    Object ref = signature_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      signature_ = s;
      return s;
    }
  }
  /**
   * <code>optional string signature = 5;</code>
   * @return The bytes for signature.
   */
  @Override
  public com.google.protobuf.ByteString
      getSignatureBytes() {
    Object ref = signature_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      signature_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNT_INCLUDE_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList accountInclude_;
  /**
   * <code>repeated string account_include = 3;</code>
   * @return A list containing the accountInclude.
   */
  public com.google.protobuf.ProtocolStringList
      getAccountIncludeList() {
    return accountInclude_;
  }
  /**
   * <code>repeated string account_include = 3;</code>
   * @return The count of accountInclude.
   */
  public int getAccountIncludeCount() {
    return accountInclude_.size();
  }
  /**
   * <code>repeated string account_include = 3;</code>
   * @param index The index of the element to return.
   * @return The accountInclude at the given index.
   */
  public String getAccountInclude(int index) {
    return accountInclude_.get(index);
  }
  /**
   * <code>repeated string account_include = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the accountInclude at the given index.
   */
  public com.google.protobuf.ByteString
      getAccountIncludeBytes(int index) {
    return accountInclude_.getByteString(index);
  }

  public static final int ACCOUNT_EXCLUDE_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList accountExclude_;
  /**
   * <code>repeated string account_exclude = 4;</code>
   * @return A list containing the accountExclude.
   */
  public com.google.protobuf.ProtocolStringList
      getAccountExcludeList() {
    return accountExclude_;
  }
  /**
   * <code>repeated string account_exclude = 4;</code>
   * @return The count of accountExclude.
   */
  public int getAccountExcludeCount() {
    return accountExclude_.size();
  }
  /**
   * <code>repeated string account_exclude = 4;</code>
   * @param index The index of the element to return.
   * @return The accountExclude at the given index.
   */
  public String getAccountExclude(int index) {
    return accountExclude_.get(index);
  }
  /**
   * <code>repeated string account_exclude = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the accountExclude at the given index.
   */
  public com.google.protobuf.ByteString
      getAccountExcludeBytes(int index) {
    return accountExclude_.getByteString(index);
  }

  public static final int ACCOUNT_REQUIRED_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList accountRequired_;
  /**
   * <code>repeated string account_required = 6;</code>
   * @return A list containing the accountRequired.
   */
  public com.google.protobuf.ProtocolStringList
      getAccountRequiredList() {
    return accountRequired_;
  }
  /**
   * <code>repeated string account_required = 6;</code>
   * @return The count of accountRequired.
   */
  public int getAccountRequiredCount() {
    return accountRequired_.size();
  }
  /**
   * <code>repeated string account_required = 6;</code>
   * @param index The index of the element to return.
   * @return The accountRequired at the given index.
   */
  public String getAccountRequired(int index) {
    return accountRequired_.get(index);
  }
  /**
   * <code>repeated string account_required = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the accountRequired at the given index.
   */
  public com.google.protobuf.ByteString
      getAccountRequiredBytes(int index) {
    return accountRequired_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, vote_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, failed_);
    }
    for (int i = 0; i < accountInclude_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, accountInclude_.getRaw(i));
    }
    for (int i = 0; i < accountExclude_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accountExclude_.getRaw(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, signature_);
    }
    for (int i = 0; i < accountRequired_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, accountRequired_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, vote_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, failed_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < accountInclude_.size(); i++) {
        dataSize += computeStringSizeNoTag(accountInclude_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAccountIncludeList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < accountExclude_.size(); i++) {
        dataSize += computeStringSizeNoTag(accountExclude_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAccountExcludeList().size();
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, signature_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < accountRequired_.size(); i++) {
        dataSize += computeStringSizeNoTag(accountRequired_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAccountRequiredList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SubscribeRequestFilterTransactions)) {
      return super.equals(obj);
    }
    SubscribeRequestFilterTransactions other = (SubscribeRequestFilterTransactions) obj;

    if (hasVote() != other.hasVote()) return false;
    if (hasVote()) {
      if (getVote()
          != other.getVote()) return false;
    }
    if (hasFailed() != other.hasFailed()) return false;
    if (hasFailed()) {
      if (getFailed()
          != other.getFailed()) return false;
    }
    if (hasSignature() != other.hasSignature()) return false;
    if (hasSignature()) {
      if (!getSignature()
          .equals(other.getSignature())) return false;
    }
    if (!getAccountIncludeList()
        .equals(other.getAccountIncludeList())) return false;
    if (!getAccountExcludeList()
        .equals(other.getAccountExcludeList())) return false;
    if (!getAccountRequiredList()
        .equals(other.getAccountRequiredList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVote()) {
      hash = (37 * hash) + VOTE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVote());
    }
    if (hasFailed()) {
      hash = (37 * hash) + FAILED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFailed());
    }
    if (hasSignature()) {
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
    }
    if (getAccountIncludeCount() > 0) {
      hash = (37 * hash) + ACCOUNT_INCLUDE_FIELD_NUMBER;
      hash = (53 * hash) + getAccountIncludeList().hashCode();
    }
    if (getAccountExcludeCount() > 0) {
      hash = (37 * hash) + ACCOUNT_EXCLUDE_FIELD_NUMBER;
      hash = (53 * hash) + getAccountExcludeList().hashCode();
    }
    if (getAccountRequiredCount() > 0) {
      hash = (37 * hash) + ACCOUNT_REQUIRED_FIELD_NUMBER;
      hash = (53 * hash) + getAccountRequiredList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SubscribeRequestFilterTransactions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeRequestFilterTransactions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeRequestFilterTransactions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeRequestFilterTransactions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeRequestFilterTransactions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeRequestFilterTransactions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeRequestFilterTransactions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SubscribeRequestFilterTransactions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SubscribeRequestFilterTransactions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SubscribeRequestFilterTransactions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SubscribeRequestFilterTransactions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SubscribeRequestFilterTransactions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SubscribeRequestFilterTransactions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geyser.SubscribeRequestFilterTransactions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geyser.SubscribeRequestFilterTransactions)
      SubscribeRequestFilterTransactionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GeyserOuterClass.internal_static_geyser_SubscribeRequestFilterTransactions_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GeyserOuterClass.internal_static_geyser_SubscribeRequestFilterTransactions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SubscribeRequestFilterTransactions.class, Builder.class);
    }

    // Construct using geyser.SubscribeRequestFilterTransactions.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      vote_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      failed_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      signature_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      accountInclude_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      accountExclude_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      accountRequired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GeyserOuterClass.internal_static_geyser_SubscribeRequestFilterTransactions_descriptor;
    }

    @Override
    public SubscribeRequestFilterTransactions getDefaultInstanceForType() {
      return SubscribeRequestFilterTransactions.getDefaultInstance();
    }

    @Override
    public SubscribeRequestFilterTransactions build() {
      SubscribeRequestFilterTransactions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SubscribeRequestFilterTransactions buildPartial() {
      SubscribeRequestFilterTransactions result = new SubscribeRequestFilterTransactions(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.vote_ = vote_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.failed_ = failed_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.signature_ = signature_;
      if (((bitField0_ & 0x00000008) != 0)) {
        accountInclude_ = accountInclude_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.accountInclude_ = accountInclude_;
      if (((bitField0_ & 0x00000010) != 0)) {
        accountExclude_ = accountExclude_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.accountExclude_ = accountExclude_;
      if (((bitField0_ & 0x00000020) != 0)) {
        accountRequired_ = accountRequired_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.accountRequired_ = accountRequired_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SubscribeRequestFilterTransactions) {
        return mergeFrom((SubscribeRequestFilterTransactions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SubscribeRequestFilterTransactions other) {
      if (other == SubscribeRequestFilterTransactions.getDefaultInstance()) return this;
      if (other.hasVote()) {
        setVote(other.getVote());
      }
      if (other.hasFailed()) {
        setFailed(other.getFailed());
      }
      if (other.hasSignature()) {
        bitField0_ |= 0x00000004;
        signature_ = other.signature_;
        onChanged();
      }
      if (!other.accountInclude_.isEmpty()) {
        if (accountInclude_.isEmpty()) {
          accountInclude_ = other.accountInclude_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureAccountIncludeIsMutable();
          accountInclude_.addAll(other.accountInclude_);
        }
        onChanged();
      }
      if (!other.accountExclude_.isEmpty()) {
        if (accountExclude_.isEmpty()) {
          accountExclude_ = other.accountExclude_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureAccountExcludeIsMutable();
          accountExclude_.addAll(other.accountExclude_);
        }
        onChanged();
      }
      if (!other.accountRequired_.isEmpty()) {
        if (accountRequired_.isEmpty()) {
          accountRequired_ = other.accountRequired_;
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ensureAccountRequiredIsMutable();
          accountRequired_.addAll(other.accountRequired_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              vote_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              failed_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              String s = input.readStringRequireUtf8();
              ensureAccountIncludeIsMutable();
              accountInclude_.add(s);
              break;
            } // case 26
            case 34: {
              String s = input.readStringRequireUtf8();
              ensureAccountExcludeIsMutable();
              accountExclude_.add(s);
              break;
            } // case 34
            case 42: {
              signature_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 42
            case 50: {
              String s = input.readStringRequireUtf8();
              ensureAccountRequiredIsMutable();
              accountRequired_.add(s);
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean vote_ ;
    /**
     * <code>optional bool vote = 1;</code>
     * @return Whether the vote field is set.
     */
    @Override
    public boolean hasVote() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool vote = 1;</code>
     * @return The vote.
     */
    @Override
    public boolean getVote() {
      return vote_;
    }
    /**
     * <code>optional bool vote = 1;</code>
     * @param value The vote to set.
     * @return This builder for chaining.
     */
    public Builder setVote(boolean value) {
      bitField0_ |= 0x00000001;
      vote_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool vote = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVote() {
      bitField0_ = (bitField0_ & ~0x00000001);
      vote_ = false;
      onChanged();
      return this;
    }

    private boolean failed_ ;
    /**
     * <code>optional bool failed = 2;</code>
     * @return Whether the failed field is set.
     */
    @Override
    public boolean hasFailed() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bool failed = 2;</code>
     * @return The failed.
     */
    @Override
    public boolean getFailed() {
      return failed_;
    }
    /**
     * <code>optional bool failed = 2;</code>
     * @param value The failed to set.
     * @return This builder for chaining.
     */
    public Builder setFailed(boolean value) {
      bitField0_ |= 0x00000002;
      failed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool failed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFailed() {
      bitField0_ = (bitField0_ & ~0x00000002);
      failed_ = false;
      onChanged();
      return this;
    }

    private Object signature_ = "";
    /**
     * <code>optional string signature = 5;</code>
     * @return Whether the signature field is set.
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string signature = 5;</code>
     * @return The signature.
     */
    public String getSignature() {
      Object ref = signature_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string signature = 5;</code>
     * @return The bytes for signature.
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      Object ref = signature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string signature = 5;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      signature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string signature = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000004);
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }
    /**
     * <code>optional string signature = 5;</code>
     * @param value The bytes for signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignatureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      signature_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList accountInclude_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAccountIncludeIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        accountInclude_ = new com.google.protobuf.LazyStringArrayList(accountInclude_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string account_include = 3;</code>
     * @return A list containing the accountInclude.
     */
    public com.google.protobuf.ProtocolStringList
        getAccountIncludeList() {
      return accountInclude_.getUnmodifiableView();
    }
    /**
     * <code>repeated string account_include = 3;</code>
     * @return The count of accountInclude.
     */
    public int getAccountIncludeCount() {
      return accountInclude_.size();
    }
    /**
     * <code>repeated string account_include = 3;</code>
     * @param index The index of the element to return.
     * @return The accountInclude at the given index.
     */
    public String getAccountInclude(int index) {
      return accountInclude_.get(index);
    }
    /**
     * <code>repeated string account_include = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the accountInclude at the given index.
     */
    public com.google.protobuf.ByteString
        getAccountIncludeBytes(int index) {
      return accountInclude_.getByteString(index);
    }
    /**
     * <code>repeated string account_include = 3;</code>
     * @param index The index to set the value at.
     * @param value The accountInclude to set.
     * @return This builder for chaining.
     */
    public Builder setAccountInclude(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAccountIncludeIsMutable();
      accountInclude_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_include = 3;</code>
     * @param value The accountInclude to add.
     * @return This builder for chaining.
     */
    public Builder addAccountInclude(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAccountIncludeIsMutable();
      accountInclude_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_include = 3;</code>
     * @param values The accountInclude to add.
     * @return This builder for chaining.
     */
    public Builder addAllAccountInclude(
        Iterable<String> values) {
      ensureAccountIncludeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, accountInclude_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_include = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountInclude() {
      accountInclude_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_include = 3;</code>
     * @param value The bytes of the accountInclude to add.
     * @return This builder for chaining.
     */
    public Builder addAccountIncludeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAccountIncludeIsMutable();
      accountInclude_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList accountExclude_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAccountExcludeIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        accountExclude_ = new com.google.protobuf.LazyStringArrayList(accountExclude_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated string account_exclude = 4;</code>
     * @return A list containing the accountExclude.
     */
    public com.google.protobuf.ProtocolStringList
        getAccountExcludeList() {
      return accountExclude_.getUnmodifiableView();
    }
    /**
     * <code>repeated string account_exclude = 4;</code>
     * @return The count of accountExclude.
     */
    public int getAccountExcludeCount() {
      return accountExclude_.size();
    }
    /**
     * <code>repeated string account_exclude = 4;</code>
     * @param index The index of the element to return.
     * @return The accountExclude at the given index.
     */
    public String getAccountExclude(int index) {
      return accountExclude_.get(index);
    }
    /**
     * <code>repeated string account_exclude = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the accountExclude at the given index.
     */
    public com.google.protobuf.ByteString
        getAccountExcludeBytes(int index) {
      return accountExclude_.getByteString(index);
    }
    /**
     * <code>repeated string account_exclude = 4;</code>
     * @param index The index to set the value at.
     * @param value The accountExclude to set.
     * @return This builder for chaining.
     */
    public Builder setAccountExclude(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAccountExcludeIsMutable();
      accountExclude_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_exclude = 4;</code>
     * @param value The accountExclude to add.
     * @return This builder for chaining.
     */
    public Builder addAccountExclude(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAccountExcludeIsMutable();
      accountExclude_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_exclude = 4;</code>
     * @param values The accountExclude to add.
     * @return This builder for chaining.
     */
    public Builder addAllAccountExclude(
        Iterable<String> values) {
      ensureAccountExcludeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, accountExclude_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_exclude = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountExclude() {
      accountExclude_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_exclude = 4;</code>
     * @param value The bytes of the accountExclude to add.
     * @return This builder for chaining.
     */
    public Builder addAccountExcludeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAccountExcludeIsMutable();
      accountExclude_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList accountRequired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAccountRequiredIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        accountRequired_ = new com.google.protobuf.LazyStringArrayList(accountRequired_);
        bitField0_ |= 0x00000020;
       }
    }
    /**
     * <code>repeated string account_required = 6;</code>
     * @return A list containing the accountRequired.
     */
    public com.google.protobuf.ProtocolStringList
        getAccountRequiredList() {
      return accountRequired_.getUnmodifiableView();
    }
    /**
     * <code>repeated string account_required = 6;</code>
     * @return The count of accountRequired.
     */
    public int getAccountRequiredCount() {
      return accountRequired_.size();
    }
    /**
     * <code>repeated string account_required = 6;</code>
     * @param index The index of the element to return.
     * @return The accountRequired at the given index.
     */
    public String getAccountRequired(int index) {
      return accountRequired_.get(index);
    }
    /**
     * <code>repeated string account_required = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the accountRequired at the given index.
     */
    public com.google.protobuf.ByteString
        getAccountRequiredBytes(int index) {
      return accountRequired_.getByteString(index);
    }
    /**
     * <code>repeated string account_required = 6;</code>
     * @param index The index to set the value at.
     * @param value The accountRequired to set.
     * @return This builder for chaining.
     */
    public Builder setAccountRequired(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAccountRequiredIsMutable();
      accountRequired_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_required = 6;</code>
     * @param value The accountRequired to add.
     * @return This builder for chaining.
     */
    public Builder addAccountRequired(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAccountRequiredIsMutable();
      accountRequired_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_required = 6;</code>
     * @param values The accountRequired to add.
     * @return This builder for chaining.
     */
    public Builder addAllAccountRequired(
        Iterable<String> values) {
      ensureAccountRequiredIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, accountRequired_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_required = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountRequired() {
      accountRequired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string account_required = 6;</code>
     * @param value The bytes of the accountRequired to add.
     * @return This builder for chaining.
     */
    public Builder addAccountRequiredBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAccountRequiredIsMutable();
      accountRequired_.add(value);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geyser.SubscribeRequestFilterTransactions)
  }

  // @@protoc_insertion_point(class_scope:geyser.SubscribeRequestFilterTransactions)
  private static final SubscribeRequestFilterTransactions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SubscribeRequestFilterTransactions();
  }

  public static SubscribeRequestFilterTransactions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscribeRequestFilterTransactions>
      PARSER = new com.google.protobuf.AbstractParser<SubscribeRequestFilterTransactions>() {
    @Override
    public SubscribeRequestFilterTransactions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubscribeRequestFilterTransactions> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SubscribeRequestFilterTransactions> getParserForType() {
    return PARSER;
  }

  @Override
  public SubscribeRequestFilterTransactions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

