// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public interface SubscribeUpdateTransactionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geyser.SubscribeUpdateTransactionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes signature = 1;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <code>bool is_vote = 2;</code>
   * @return The isVote.
   */
  boolean getIsVote();

  /**
   * <code>.solana.storage.ConfirmedBlock.Transaction transaction = 3;</code>
   * @return Whether the transaction field is set.
   */
  boolean hasTransaction();
  /**
   * <code>.solana.storage.ConfirmedBlock.Transaction transaction = 3;</code>
   * @return The transaction.
   */
  solana.storage.ConfirmedBlock.Transaction getTransaction();
  /**
   * <code>.solana.storage.ConfirmedBlock.Transaction transaction = 3;</code>
   */
  solana.storage.ConfirmedBlock.TransactionOrBuilder getTransactionOrBuilder();

  /**
   * <code>.solana.storage.ConfirmedBlock.TransactionStatusMeta meta = 4;</code>
   * @return Whether the meta field is set.
   */
  boolean hasMeta();
  /**
   * <code>.solana.storage.ConfirmedBlock.TransactionStatusMeta meta = 4;</code>
   * @return The meta.
   */
  solana.storage.ConfirmedBlock.TransactionStatusMeta getMeta();
  /**
   * <code>.solana.storage.ConfirmedBlock.TransactionStatusMeta meta = 4;</code>
   */
  solana.storage.ConfirmedBlock.TransactionStatusMetaOrBuilder getMetaOrBuilder();

  /**
   * <code>uint64 index = 5;</code>
   * @return The index.
   */
  long getIndex();
}
