// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

public interface SubscribeUpdateAccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geyser.SubscribeUpdateAccount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.geyser.SubscribeUpdateAccountInfo account = 1;</code>
   * @return Whether the account field is set.
   */
  boolean hasAccount();
  /**
   * <code>.geyser.SubscribeUpdateAccountInfo account = 1;</code>
   * @return The account.
   */
  SubscribeUpdateAccountInfo getAccount();
  /**
   * <code>.geyser.SubscribeUpdateAccountInfo account = 1;</code>
   */
  SubscribeUpdateAccountInfoOrBuilder getAccountOrBuilder();

  /**
   * <code>uint64 slot = 2;</code>
   * @return The slot.
   */
  long getSlot();

  /**
   * <code>bool is_startup = 3;</code>
   * @return The isStartup.
   */
  boolean getIsStartup();
}
