// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geyser.proto

package geyser;

/**
 * Protobuf type {@code geyser.SubscribeUpdateAccountInfo}
 */
public final class SubscribeUpdateAccountInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geyser.SubscribeUpdateAccountInfo)
    SubscribeUpdateAccountInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubscribeUpdateAccountInfo.newBuilder() to construct.
  private SubscribeUpdateAccountInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubscribeUpdateAccountInfo() {
    pubkey_ = com.google.protobuf.ByteString.EMPTY;
    owner_ = com.google.protobuf.ByteString.EMPTY;
    data_ = com.google.protobuf.ByteString.EMPTY;
    txnSignature_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubscribeUpdateAccountInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GeyserOuterClass.internal_static_geyser_SubscribeUpdateAccountInfo_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GeyserOuterClass.internal_static_geyser_SubscribeUpdateAccountInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SubscribeUpdateAccountInfo.class, Builder.class);
  }

  private int bitField0_;
  public static final int PUBKEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString pubkey_;
  /**
   * <code>bytes pubkey = 1;</code>
   * @return The pubkey.
   */
  @Override
  public com.google.protobuf.ByteString getPubkey() {
    return pubkey_;
  }

  public static final int LAMPORTS_FIELD_NUMBER = 2;
  private long lamports_;
  /**
   * <code>uint64 lamports = 2;</code>
   * @return The lamports.
   */
  @Override
  public long getLamports() {
    return lamports_;
  }

  public static final int OWNER_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString owner_;
  /**
   * <code>bytes owner = 3;</code>
   * @return The owner.
   */
  @Override
  public com.google.protobuf.ByteString getOwner() {
    return owner_;
  }

  public static final int EXECUTABLE_FIELD_NUMBER = 4;
  private boolean executable_;
  /**
   * <code>bool executable = 4;</code>
   * @return The executable.
   */
  @Override
  public boolean getExecutable() {
    return executable_;
  }

  public static final int RENT_EPOCH_FIELD_NUMBER = 5;
  private long rentEpoch_;
  /**
   * <code>uint64 rent_epoch = 5;</code>
   * @return The rentEpoch.
   */
  @Override
  public long getRentEpoch() {
    return rentEpoch_;
  }

  public static final int DATA_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes data = 6;</code>
   * @return The data.
   */
  @Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int WRITE_VERSION_FIELD_NUMBER = 7;
  private long writeVersion_;
  /**
   * <code>uint64 write_version = 7;</code>
   * @return The writeVersion.
   */
  @Override
  public long getWriteVersion() {
    return writeVersion_;
  }

  public static final int TXN_SIGNATURE_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString txnSignature_;
  /**
   * <code>optional bytes txn_signature = 8;</code>
   * @return Whether the txnSignature field is set.
   */
  @Override
  public boolean hasTxnSignature() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bytes txn_signature = 8;</code>
   * @return The txnSignature.
   */
  @Override
  public com.google.protobuf.ByteString getTxnSignature() {
    return txnSignature_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!pubkey_.isEmpty()) {
      output.writeBytes(1, pubkey_);
    }
    if (lamports_ != 0L) {
      output.writeUInt64(2, lamports_);
    }
    if (!owner_.isEmpty()) {
      output.writeBytes(3, owner_);
    }
    if (executable_ != false) {
      output.writeBool(4, executable_);
    }
    if (rentEpoch_ != 0L) {
      output.writeUInt64(5, rentEpoch_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(6, data_);
    }
    if (writeVersion_ != 0L) {
      output.writeUInt64(7, writeVersion_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBytes(8, txnSignature_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!pubkey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, pubkey_);
    }
    if (lamports_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, lamports_);
    }
    if (!owner_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, owner_);
    }
    if (executable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, executable_);
    }
    if (rentEpoch_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, rentEpoch_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, data_);
    }
    if (writeVersion_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, writeVersion_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, txnSignature_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SubscribeUpdateAccountInfo)) {
      return super.equals(obj);
    }
    SubscribeUpdateAccountInfo other = (SubscribeUpdateAccountInfo) obj;

    if (!getPubkey()
        .equals(other.getPubkey())) return false;
    if (getLamports()
        != other.getLamports()) return false;
    if (!getOwner()
        .equals(other.getOwner())) return false;
    if (getExecutable()
        != other.getExecutable()) return false;
    if (getRentEpoch()
        != other.getRentEpoch()) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (getWriteVersion()
        != other.getWriteVersion()) return false;
    if (hasTxnSignature() != other.hasTxnSignature()) return false;
    if (hasTxnSignature()) {
      if (!getTxnSignature()
          .equals(other.getTxnSignature())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
    hash = (53 * hash) + getPubkey().hashCode();
    hash = (37 * hash) + LAMPORTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLamports());
    hash = (37 * hash) + OWNER_FIELD_NUMBER;
    hash = (53 * hash) + getOwner().hashCode();
    hash = (37 * hash) + EXECUTABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getExecutable());
    hash = (37 * hash) + RENT_EPOCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRentEpoch());
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + WRITE_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWriteVersion());
    if (hasTxnSignature()) {
      hash = (37 * hash) + TXN_SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getTxnSignature().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SubscribeUpdateAccountInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeUpdateAccountInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeUpdateAccountInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeUpdateAccountInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeUpdateAccountInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscribeUpdateAccountInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscribeUpdateAccountInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SubscribeUpdateAccountInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SubscribeUpdateAccountInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SubscribeUpdateAccountInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SubscribeUpdateAccountInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SubscribeUpdateAccountInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SubscribeUpdateAccountInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geyser.SubscribeUpdateAccountInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geyser.SubscribeUpdateAccountInfo)
      SubscribeUpdateAccountInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GeyserOuterClass.internal_static_geyser_SubscribeUpdateAccountInfo_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GeyserOuterClass.internal_static_geyser_SubscribeUpdateAccountInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SubscribeUpdateAccountInfo.class, Builder.class);
    }

    // Construct using geyser.SubscribeUpdateAccountInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      pubkey_ = com.google.protobuf.ByteString.EMPTY;

      lamports_ = 0L;

      owner_ = com.google.protobuf.ByteString.EMPTY;

      executable_ = false;

      rentEpoch_ = 0L;

      data_ = com.google.protobuf.ByteString.EMPTY;

      writeVersion_ = 0L;

      txnSignature_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GeyserOuterClass.internal_static_geyser_SubscribeUpdateAccountInfo_descriptor;
    }

    @Override
    public SubscribeUpdateAccountInfo getDefaultInstanceForType() {
      return SubscribeUpdateAccountInfo.getDefaultInstance();
    }

    @Override
    public SubscribeUpdateAccountInfo build() {
      SubscribeUpdateAccountInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SubscribeUpdateAccountInfo buildPartial() {
      SubscribeUpdateAccountInfo result = new SubscribeUpdateAccountInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.pubkey_ = pubkey_;
      result.lamports_ = lamports_;
      result.owner_ = owner_;
      result.executable_ = executable_;
      result.rentEpoch_ = rentEpoch_;
      result.data_ = data_;
      result.writeVersion_ = writeVersion_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.txnSignature_ = txnSignature_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SubscribeUpdateAccountInfo) {
        return mergeFrom((SubscribeUpdateAccountInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SubscribeUpdateAccountInfo other) {
      if (other == SubscribeUpdateAccountInfo.getDefaultInstance()) return this;
      if (other.getPubkey() != com.google.protobuf.ByteString.EMPTY) {
        setPubkey(other.getPubkey());
      }
      if (other.getLamports() != 0L) {
        setLamports(other.getLamports());
      }
      if (other.getOwner() != com.google.protobuf.ByteString.EMPTY) {
        setOwner(other.getOwner());
      }
      if (other.getExecutable() != false) {
        setExecutable(other.getExecutable());
      }
      if (other.getRentEpoch() != 0L) {
        setRentEpoch(other.getRentEpoch());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      if (other.getWriteVersion() != 0L) {
        setWriteVersion(other.getWriteVersion());
      }
      if (other.hasTxnSignature()) {
        setTxnSignature(other.getTxnSignature());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pubkey_ = input.readBytes();

              break;
            } // case 10
            case 16: {
              lamports_ = input.readUInt64();

              break;
            } // case 16
            case 26: {
              owner_ = input.readBytes();

              break;
            } // case 26
            case 32: {
              executable_ = input.readBool();

              break;
            } // case 32
            case 40: {
              rentEpoch_ = input.readUInt64();

              break;
            } // case 40
            case 50: {
              data_ = input.readBytes();

              break;
            } // case 50
            case 56: {
              writeVersion_ = input.readUInt64();

              break;
            } // case 56
            case 66: {
              txnSignature_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString pubkey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes pubkey = 1;</code>
     * @return The pubkey.
     */
    @Override
    public com.google.protobuf.ByteString getPubkey() {
      return pubkey_;
    }
    /**
     * <code>bytes pubkey = 1;</code>
     * @param value The pubkey to set.
     * @return This builder for chaining.
     */
    public Builder setPubkey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pubkey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes pubkey = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPubkey() {
      
      pubkey_ = getDefaultInstance().getPubkey();
      onChanged();
      return this;
    }

    private long lamports_ ;
    /**
     * <code>uint64 lamports = 2;</code>
     * @return The lamports.
     */
    @Override
    public long getLamports() {
      return lamports_;
    }
    /**
     * <code>uint64 lamports = 2;</code>
     * @param value The lamports to set.
     * @return This builder for chaining.
     */
    public Builder setLamports(long value) {
      
      lamports_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 lamports = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLamports() {
      
      lamports_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString owner_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes owner = 3;</code>
     * @return The owner.
     */
    @Override
    public com.google.protobuf.ByteString getOwner() {
      return owner_;
    }
    /**
     * <code>bytes owner = 3;</code>
     * @param value The owner to set.
     * @return This builder for chaining.
     */
    public Builder setOwner(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      owner_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes owner = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwner() {
      
      owner_ = getDefaultInstance().getOwner();
      onChanged();
      return this;
    }

    private boolean executable_ ;
    /**
     * <code>bool executable = 4;</code>
     * @return The executable.
     */
    @Override
    public boolean getExecutable() {
      return executable_;
    }
    /**
     * <code>bool executable = 4;</code>
     * @param value The executable to set.
     * @return This builder for chaining.
     */
    public Builder setExecutable(boolean value) {
      
      executable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool executable = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutable() {
      
      executable_ = false;
      onChanged();
      return this;
    }

    private long rentEpoch_ ;
    /**
     * <code>uint64 rent_epoch = 5;</code>
     * @return The rentEpoch.
     */
    @Override
    public long getRentEpoch() {
      return rentEpoch_;
    }
    /**
     * <code>uint64 rent_epoch = 5;</code>
     * @param value The rentEpoch to set.
     * @return This builder for chaining.
     */
    public Builder setRentEpoch(long value) {
      
      rentEpoch_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 rent_epoch = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRentEpoch() {
      
      rentEpoch_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 6;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 6;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes data = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private long writeVersion_ ;
    /**
     * <code>uint64 write_version = 7;</code>
     * @return The writeVersion.
     */
    @Override
    public long getWriteVersion() {
      return writeVersion_;
    }
    /**
     * <code>uint64 write_version = 7;</code>
     * @param value The writeVersion to set.
     * @return This builder for chaining.
     */
    public Builder setWriteVersion(long value) {
      
      writeVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 write_version = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearWriteVersion() {
      
      writeVersion_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString txnSignature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes txn_signature = 8;</code>
     * @return Whether the txnSignature field is set.
     */
    @Override
    public boolean hasTxnSignature() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes txn_signature = 8;</code>
     * @return The txnSignature.
     */
    @Override
    public com.google.protobuf.ByteString getTxnSignature() {
      return txnSignature_;
    }
    /**
     * <code>optional bytes txn_signature = 8;</code>
     * @param value The txnSignature to set.
     * @return This builder for chaining.
     */
    public Builder setTxnSignature(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      txnSignature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes txn_signature = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTxnSignature() {
      bitField0_ = (bitField0_ & ~0x00000001);
      txnSignature_ = getDefaultInstance().getTxnSignature();
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geyser.SubscribeUpdateAccountInfo)
  }

  // @@protoc_insertion_point(class_scope:geyser.SubscribeUpdateAccountInfo)
  private static final SubscribeUpdateAccountInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SubscribeUpdateAccountInfo();
  }

  public static SubscribeUpdateAccountInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscribeUpdateAccountInfo>
      PARSER = new com.google.protobuf.AbstractParser<SubscribeUpdateAccountInfo>() {
    @Override
    public SubscribeUpdateAccountInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubscribeUpdateAccountInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SubscribeUpdateAccountInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public SubscribeUpdateAccountInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

